### ISSUE TITLE
wytruerand "secret" [question]

### ISSUE THREAD

**Issue by cocowalla** [wangyi-fudan/wyhash#10]
The `wytruerand` function takes as parameters both a seed and a "secret" - I was wondering about the purpose of this, and whether it is indeed intended to be kept, well, "secret"?

**Comment by wangyi-fudan** [comment]
basicly wytruerand is experimental. I add the secret parameter to make it more personalized. However, I am not sure whether it is necessary. Also it is not proved that the secret will be well kept. anyway, due to the uncertainty and the long run time of clock(), wytruerand is almost true random.

**Comment by cocowalla** [comment]
OK, thanks for the quick response!

I'm porting wyhash and wyrand to C#, but I'll leave wytruerand out for now.
