### ISSUE TITLE
Hashing a file, by chunks

### ISSUE THREAD

**Issue by fcorbelli** [wangyi-fudan/wyhash#102]
Is it possible to use wyhash to compute an overall hash of a file, with something like that (snippet)?

```
	FILE* myfile = freadopen(i_filename);
	(...)	
	char data[65536*16];
        int got=0;
	
	uint64_t hash;
	uint64_t _wyp[4];
	make_secret(345,_wyp);
	
	while ((got=fread(data,sizeof(char),sizeof(data),myfile)) > 0) 
	{
		hash=wyhash(data,got,hash,_wyp);
/// 	something like (void)XXH3_128bits_update(&state128, buffer, readSize);
	}
	fclose(myfile);
	
	char temp[33];
	sprintf(temp,"%016llX",(unsigned long long)hash);
```

Thanks

**Comment by lemire** [comment]
Definitively possible, but currently undocumented as far as I can tell.

**Comment by lemire** [comment]
Note that the presence of a file is a red herring.

**Comment by fcorbelli** [comment]
Hashing by chunks is very common, mandatory when working with files.
It depends on the state of the hasher, and I am not sure at all if wyhash can be used like I do
The parameters are
```
static inline uint64_t wyhash(const void *key, size_t len, uint64_t seed, const uint64_t *secret){
```
key and len, OK (new chunk of data and size) but seed and secret?
Can the i-1 chunked hash used as seed for the i chunk, to get a streamed hash?

**Comment by lemire** [comment]
> Hashing by chunks is very common, mandatory when working with files.

Yes, hashing by chunks is common. (Whether it is "mandatory" with files depends on the size of the files.)

It is done with `wyhash_init`,  `wyhash_update` and `wyhash_final `.

https://github.com/wangyi-fudan/wyhash/blob/896d7c57f68d96938f718c0695c44866d14b48d6/old_versions/wyhash_v5.h#L244

**Comment by fcorbelli** [comment]
Those seems functions for old version, stripped in the last one.
Can be ported to the last?

Thank you

**Comment by cocowalla** [comment]
See #28 for some earlier discussion.

**Comment by fcorbelli** [comment]
So if understand right the short version is : wyhash cannot be used to get the hash of a file by chunks. 
This make wyhash useless in many user case

**Comment by trapexit** [comment]
Of course it can. You simply take the output of each chunk hashing and place into the seed for the next call. Same as pretty much any other hash function.

**Comment by fcorbelli** [comment]
https://github.com/wangyi-fudan/wyhash/issues/28

**Comment by trapexit** [comment]
I'm not sure what you're trying to show.

1) The hash isn't intended for large sets of data. It's meant to be a fast short data hash such as those needed in data structures. A single hash does not need to be best in class for all usecases.
2) You *can* use wyhash to hash a file in chunks. There isn't some randomness in the behavior is there? The fact that the output is different depending on the chunk size is something to note and may matter in certain situations but doesn't mean it can't be used. Think of the chunk size as part of the seed.

**Comment by fcorbelli** [comment]
I am only tryng to show that this hash is unfit for my needs.
Nothing more.
thank you for this confirmation

**Comment by cocowalla** [comment]
> So if understand right the short version is : wyhash cannot be used to get the hash of a file by chunks.
> This make wyhash useless in many user case

That's not the case. I think Wang Yi may have unintentionally confused things in #28 with the way he closed it.

WyHash was indeed designed for short values, but you **can** use WyHash to hash files a block at a time - just hold off on calling the finalizer function until the last block.

The only thing is that you're not going to get the same result as if you hashed the whole file. I presume your hashing is internal (as in, you will not be exposing hashes to 3rd parties), in which case it's not really an issue, as long as you always use the same block size (e.g. 64K).

**Comment by lemire** [comment]
This needs to be documented.

**Comment by wangyi-fudan** [comment]
thank you for discussions. I explain what I think.
If we want has a file, we can use mmap function (under Linux) first to map it to virual memory, then call wyhash.
many hash functions have continuing hashing ability. That's a good feature. However, wyhash experiences many changes in order the achieve speed. I don't want to maintain a continuing hash interface right now as a burden. When wyhash stop changing (died) we can build such interface for it.

**Comment by fcorbelli** [comment]
In fact I try wyhash to check file integrity and equality

https://github.com/fcorbelli/zpaqfranz

And, after all, runs not so bad.
You can try with something like
zpaqfranz sha1 k:\*.mp4 -wyhash -all
and
zpaqfranz sha1 k:\*.mp4 -xxh3 -all
(-all for SSD not for spinning drive) 
But if the hash change upon block size then it is not fit (for my needs)

**Comment by fcorbelli** [comment]
Quick comparing of **XXH3** vs wyhash on files
```
C:\zpaqfranz>zpaqfranz sha1 k:\*.mp4 -xxh3 -all -summary
zpaqfranz v52.9-experimental snapshot archiver, compiled Jul 22 2021
franz:XXH3 (-xxh3)
franz:summary    1
Getting XXH3 ignoring .zfs and :$DATA
Computing filesize for 1 files/directory...
Found (7.06 GB) => 7.586.033.545 bytes (7.06 GB) / 6 files in 0.000000

Creating 32 hashing thread(s)
001% 00:00:01 (  72.38 MB) of (   7.06 GB)           75.890.688 /sec
(...)
Algo XXH3 by 32 threads
Scanning filesystem time  0.000000 s
Data transfer+CPU   time  0.407000 s
Data output         time  0.000000 s
Total size                      7.586.033.545 (   7.06 GB)
Tested size                     7.586.033.545 (   7.06 GB)
Duplicated size                             0 (    0.00 B)
Duplicated files                            0
Worked on 7.586.033.545 bytes avg speed (hashtime) 18.638.903.058 B/s
GLOBAL SHA256: 93A057E28EEDCDDBE60279EED66F1B82EA702C86202B6391F4F717A506DA0504
```

**Vs wyhash**
```
C:\zpaqfranz>zpaqfranz sha1 k:\*.mp4 -wyhash -all -summary
zpaqfranz v52.9-experimental snapshot archiver, compiled Jul 22 2021
franz:wyhash
franz:summary    1
Getting WYHASH ignoring .zfs and :$DATA
Computing filesize for 1 files/directory...
Found (7.06 GB) => 7.586.033.545 bytes (7.06 GB) / 6 files in 0.000000

Creating 32 hashing thread(s)
001% 00:00:01 (  73.00 MB) of (   7.06 GB)           76.546.048 /sec
(...)
Algo WYHASH by 32 threads
Scanning filesystem time  0.000000 s
Data transfer+CPU   time  0.392000 s
Data output         time  0.000000 s
Total size                      7.586.033.545 (   7.06 GB)
Tested size                     7.586.033.545 (   7.06 GB)
Duplicated size                             0 (    0.00 B)
Duplicated files                            0
Worked on 7.586.033.545 bytes avg speed (hashtime) 19.352.126.390 B/s
GLOBAL SHA256: ECCAB603CF3435238E9EFB1B861D251CDD58BF622B2CE48B8244C0885AE74A12
```


Just for reference SHA-1  

```
C:\zpaqfranz>zpaqfranz sha1 k:\*.mp4 -sha1 -all -summary
zpaqfranz v52.9-experimental snapshot archiver, compiled Jul 22 2021
franz:SHA-1 (-sha1)
franz:summary    1
Getting SHA1 ignoring .zfs and :$DATA
Computing filesize for 1 files/directory...
Found (7.06 GB) => 7.586.033.545 bytes (7.06 GB) / 6 files in 0.016000

Creating 32 hashing thread(s)
001% 00:00:04 (  72.50 MB) of (   7.06 GB)           76.021.760 /sec
(...)
Algo SHA1 by 32 threads
Scanning filesystem time  0.016000 s
Data transfer+CPU   time  4.329000 s
Data output         time  0.000000 s
Total size                      7.586.033.545 (   7.06 GB)
Tested size                     7.586.033.545 (   7.06 GB)
Duplicated size                             0 (    0.00 B)
Duplicated files                            0
Worked on 7.586.033.545 bytes avg speed (hashtime) 1.752.375.501 B/s
GLOBAL SHA256: 060F56BA765264CC37A892E3DE1A4C795489884E46EA1CB4B0F75C0D05032E9C
```

**=> wyhash run fast (at least in this not-so-good mode) even in chunked hashing.**

Maybe it's a possibility to consider (memory mapped files are essentially unusable for archivers)

**Comment by fcorbelli** [comment]
```
Fast, but unreliable (to detect duplication)

Algo XXHASH64 by 32 threads
Scanning filesystem time  4.797000 s
Data transfer+CPU   time  158.845000 s
Data output         time  0.266000 s
Total size                    467.205.895.805 ( 435.12 GB)
Tested size                    87.357.301.688 (  81.36 GB)
Duplicated size                35.200.896.300 (  32.78 GB)
Duplicated files                       45.462
Worked on 87.357.301.688 bytes avg speed (hashtime) 549.953.109 B/s

Algo SHA-256 by 32 threads
Scanning filesystem time  4.485000 s
Data transfer+CPU   time  159.095000 s
Data output         time  0.297000 s
Total size                    467.205.895.805 ( 435.12 GB)
Tested size                    87.357.301.688 (  81.36 GB)
Duplicated size                35.200.896.300 (  32.78 GB)
Duplicated files                       45.462
Worked on 87.357.301.688 bytes avg speed (hashtime) 549.088.919 B/s


Algo WYHASH by 32 threads
Scanning filesystem time  4.703000 s
Data transfer+CPU   time  154.361000 s
Data output         time  0.281000 s
Total size                    467.205.895.805 ( 435.12 GB)
Tested size                    87.357.301.688 (  81.36 GB)
Duplicated size                         1.411 (   1.38 KB)
Duplicated files                        6.980
```

**Comment by bigerl** [comment]
@fcorbelli What exactly is the task solved in the duplicate detection benchmark you posted?
Do you have any lead why whhash is performing bad? 
Are you sure it a) provides the necessary functionality required for this task and b) is correctly used?
I am pondering because the other two algorithms find the exact same duplicated size and number of files; which might be a hint that it should actually be an deterministic task.

**Comment by fcorbelli** [comment]
You are right, it is a deduplication search.
Using other algorithms (in fact SHA-256 is more then enough) the result should be identical.
No more, no less.
And
a) I do not know (it is what I am asking in this thread, first post)
b) I do not know (it is what I am asking in this thread, first post)
So yes, there is something wrong in either the use of wyhash (I think 99.999999999999999%) or in wyhash itself (0.00000000000000000001%)

**Comment by fcorbelli** [comment]
OK I made my chunker-memory-mapped-Windows-64 test
```
string wyhash_calc_file(const char * i_filename,bool i_flagcalccrc32,uint32_t& o_crc32,const int64_t i_inizio,const int64_t i_totali,int64_t& io_lavorati)
{
	
	o_crc32=0;
	string risultato="ERROR";
	
	wstring wfilename=utow(i_filename);
	HANDLE myfile=CreateFile(wfilename.c_str(), GENERIC_READ, FILE_SHARE_READ | FILE_SHARE_WRITE, 0, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, 0);
	if (myfile==INVALID_HANDLE_VALUE) 
	{
		printf("25057: Invalid handle for %s\n",i_filename);
		return "ERROR";
	}
	uint64_t lunghezza=GetFileSize(myfile,0);
	HANDLE mapping=CreateFileMapping(myfile,0,PAGE_READONLY, 0, 0, 0);
	if (mapping==0) 
		return "ERROR";
	const char* data = (const char*) MapViewOfFile(mapping, FILE_MAP_READ, 0, 0, 0);
	if(data)
	{
		///printf("Thinking... %s\n",i_filename);
		uint64_t _wyp[4];
		make_secret(345,_wyp);
		uint64_t mywyhash=wyhash(data,lunghezza,0,_wyp);
		char buffer[33]={0};
		sprintf(buffer,"%16llX",mywyhash);
		risultato=buffer;
		///printf("%s\n",risultato.c_str());
		if (i_flagcalccrc32)
		{
			printf("Thinking on CRC-32\n");
			o_crc32=crc32_16bytes(data,lunghezza,o_crc32);
 		}
		io_lavorati+=lunghezza;	
	}
	else
	{
		printf("25095: data empty\n");
		return "ERROR";
	}	
    
	UnmapViewOfFile(data);
	CloseHandle(mapping);
	CloseHandle(myfile);
	return risultato;
}
```

with those results
WYHASH (memory mapped)

```
C:\zpaqfranz>zpaqfranz sha1 c:\dropbox\dropbox -wyhash -all -summary
zpaqfranz v52.9-experimental snapshot archiver, compiled Jul 23 2021


****** WARNING: WYHASH IMPLEMENTATION IS BROKEN *******
****** JUST FOR TEST !!! *******
franz:wyhash
franz:summary    1
Getting WYHASH ignoring .zfs and :$DATA

Found (8.20 GB) => 8.807.113.288 bytes (8.20 GB) / 21.519 files in 0.218000

Creating 32 hashing thread(s) with WYHASH
Scanning filesystem time            0.218 s
Data transfer+CPU   time            1.642 s
Data output         time            0.000 s
Total size                      8.807.113.288 (   8.20 GB)
Tested size                     8.807.113.288 (   8.20 GB)
Duplicated size                   264.663.198 ( 252.40 MB)
Duplicated files                        4.094
Worked on 8.807.113.288 bytes avg speed (hashtime) 5.363.649.992 B/s
GLOBAL SHA256: 77112A6A2EA247EA87E713BD61409FEA3760B22305924454D73FF20FB7DD5970

1.922 seconds (all OK)
```

**Cumulative speed: 5.3GB/s**

SHA-256 (reference to check the "goodness" of wyhas)  
```
C:\zpaqfranz>zpaqfranz sha1 c:\dropbox\dropbox -sha256 -all -summary
zpaqfranz v52.9-experimental snapshot archiver, compiled Jul 23 2021
...
Creating 32 hashing thread(s) with SHA-256
...
Scanning filesystem time            0.203 s
Data transfer+CPU   time            4.532 s
Data output         time            0.015 s
Total size                      8.807.113.288 (   8.20 GB)
Tested size                     8.807.113.288 (   8.20 GB)
Duplicated size                   264.663.198 ( 252.40 MB)
Duplicated files                        4.094
Worked on 8.807.113.288 bytes avg speed (hashtime) 1.943.317.142 B/s
```
Note duplicated size and cardinality

Then XXH3

```
C:\zpaqfranz>zpaqfranz sha1 c:\dropbox\dropbox -xxh3 -all -summary
...
Creating 32 hashing thread(s) with XXH3
Scanning filesystem time            0.219 s
Data transfer+CPU   time            0.439 s
Data output         time            0.015 s
Total size                      8.807.113.288 (   8.20 GB)
Tested size                     8.807.113.288 (   8.20 GB)
Duplicated size                   264.663.198 ( 252.40 MB)
Duplicated files                        4.094
Worked on 8.807.113.288 bytes avg speed (hashtime) 20.061.761.476 B/s
GLOBAL SHA256: 9079E18B3940CB6C1FE918C2B72C6E0C31D47E49CD67137F6ADA8F7FCDE70D7B
```

**With chunked-file: 20GB/s**

**Comment by fcorbelli** [comment]
As expected, the use of memory mapped files reduces the speed by about a factor of 4, falling back from ~19GB/s to 5GB/s in "real world".
It is bad, but patience, testing in progress


What I would like to know is the **seed** and the **secret**.
For this use (calculate the hash of large files, hundreds of GB), how to choose?  
In my case I put 0 and 345, but which ones?  
Thank you

```
uint64_t _wyp[4];
make_secret(345,_wyp);
uint64_t mywyhash=wyhash(data,lunghezza,0,_wyp);
```

**Comment by wangyi-fudan** [comment]
The speed drop is because you actually read from hard driver first. later XXH3 speed is because the data is already in the memory.
345 initialize the secret _wyp.
0 is the seed.

**Comment by fcorbelli** [comment]
In fact no, I do not read anything from disk (it's a RAMDISK cached by OS) in either case.
The limit seems the OS that cannot read many concurrent memory mapped file, against "regular" files.

I know that 345 is the secret and 0 is the seed.
But my question is:

can I use whatever seed and whatever secret I want?
For example 0 and 0


```
Some other tests (Windows 64, RAMDISK, MAX speed)
1 thread
wyhash (MM) ~4.9GB/s
xxhash64 (chunk) ~5.1GB/s
xxh3 (128) ~5.3GB/s

4 threads
wyhash 8.3GB/s  ==>>> OS limit for mapped files?
xxhash64 13GB/s
xxh3 15GB/s

16 threads
wyhash 6.2GB/s
xxhash64 21GB/s
xxh3 22GB/s
```

**Comment by wangyi-fudan** [comment]
yes, any 64 bit integer will be fine for seed and secret. 
another point is that you should make_secret offline and save the _wyp for later frequent usage (it is your own secret). make_secret is a bit time consuming. on the other hand seed can be used and changed at run time

**Comment by fcorbelli** [comment]
In fact I do not need a secret at all.
When running wyhash with big files (in this examples >4GB just to be sure to surpass 32 bit limit) the speed is indeed remarkable, 29GB/s for ONE thread is much faster then 6GB/s for thread of XXH3.

But, as previously stated, the memory-mapped access reduce (by far) the performance when doing a large-scale hashing (ex. deduplication)

```
Z:\>c:\zpaqfranz\zpaqfranz sha1 z:\* -wyhash
zpaqfranz v52.9-experimental snapshot archiver, compiled Jul 23 2021


****** WARNING: WYHASH IMPLEMENTATION IS BROKEN *******
****** JUST FOR TEST !!! *******
franz:wyhash
Getting WYHASH ignoring .zfs and :$DATA

z:/System Volume Information/*: error access denied

Found (14.89 GB) => 15.983.575.040 bytes (14.89 GB) / 3 files in 0.015000

Creating 1 hashing thread(s) with WYHASH
WYHASH: 3ABBFB0F8417F88D [      5.844.303.872]     z:/bsd130 - Copia.vmdk
WYHASH: 3ABBFB0F8417F88D [      5.844.303.872] === z:/bsd130.vmdk
WYHASH: 978A672049F84634 [      4.294.967.296]     z:/test.vmem
Scanning filesystem time            0.015 s
Data transfer+CPU   time            0.548 s
Data output         time            0.016 s
Total size                     15.983.575.040 (  14.89 GB)
Tested size                    15.983.575.040 (  14.89 GB)
Duplicated size                 5.844.303.872 (   5.44 GB)
Duplicated files                            1
Worked on 15.983.575.040 bytes avg speed (hashtime) 29.167.107.737 B/s



Getting XXH3 ignoring .zfs and :$DATA

z:/System Volume Information/*: error access denied

Found (14.89 GB) => 15.983.575.040 bytes (14.89 GB) / 3 files in 0.000000

Creating 1 hashing thread(s) with XXH3
...
XXH3: 30033CD79EA1E874D5F931C2DC5477DA [      4.294.967.296]     z:/test.vmem
XXH3: 579194A00172C6C2163AE802F4A138AF [      5.844.303.872]     z:/bsd130 - Copia.vmdk
XXH3: 579194A00172C6C2163AE802F4A138AF [      5.844.303.872] === z:/bsd130.vmdk
Scanning filesystem time            0.000 s
Data transfer+CPU   time            2.626 s
Data output         time            0.016 s
Total size                     15.983.575.040 (  14.89 GB)
Tested size                    15.983.575.040 (  14.89 GB)
Duplicated size                 5.844.303.872 (   5.44 GB)
Duplicated files                            1
Worked on 15.983.575.040 bytes avg speed (hashtime) 6.086.662.239 B/s
```

**Comment by cocowalla** [comment]
> But, as previously stated, the memory-mapped access reduce (by far) the performance

I noticed you were on Windows. Not sure if it's your issue here, but I've previously noticed that reading single MMFs on Windows is *slower* than reading the file normally, although nothing like 4x slower

**Comment by fcorbelli** [comment]
For the curious here is an update of my archiver which also uses wyhash (with mapped files).  
Just for fun and to see it working compared to others (should compile on Windows, Linux and FreeBSD by g++)  
https://github.com/fcorbelli/zpaqfranz

For lazy windows users here the binaries
https://sourceforge.net/projects/zpaqfranz/files/  

Just speed check (check duplicated files in folder z:\knb)
```
zpaqfranz sha1 z:\knb -wyhash -summary
```

Multithread (for SSDs)
```
zpaqfranz sha1 z:\knb -wyhash -all -summary
```
Multithread (for SSDs), limited to **X** thread
```
zpaqfranz sha1 z:\knb -wyhash -all -tX -summary
```

Instead of -wyhash, just for fun you can use

- -sha1 (rather fast implementation)
- -sha256 (good, but heavy)
- -xxhash (Brumme's xxhash64 of Collet's)
- -xxh3 (Collet's XXH3)
- -crc32 (Ziganshin's slice by 16)
- -crc32c (Adler's HW acceleration)

**WARNING: other hashes use the "normal" chunked read of files (with different buffer size).
wyhash, instead, use memory mapped file. So heavy OS overhead takes place.**

Other examples
```
zpaqfranz sha1 k:\*.mp4 -xxh3 -all
```

or
```
zpaqfranz ? sha1  
```

**Comment by tansy** [comment]
As I've been called to blackboard I feel obliged to answer shortly. Yes, wyhash is not rolling hash, it cannot "pause and resume after stopping for a break". It is not a problem as it's been designed to process lots of relatively small strings rather than large chunks of streaming data. It's not an issue, it's a feature.
And yes you can, as suggested earlier, not to finalise the hash and be able to make it rolling, but it will be different hash. If you are intending to use out internally the it will not be an issu. If you do need to share it outside then there are other hashes designed for the purpose and you should turn to them.

**Comment by fcorbelli** [comment]
Thank you, but I already did, via memory mapped files.  
A bit of overhead, but indeed doable, to get something like "md5sum" or "sha1sum" or whatever.  
```
P:\>c:\zpaqfranz\zpaqfranz sum c:\dropbox\dropbox -xxh3 -all -summary
zpaqfranz v54.10-experimental (HW BLAKE3), SFX64 v52.15, compiled Dec 20 2021
franz:-xxh3 -summary
Getting XXH3 ignoring .zfs and :$DATA

Found (8.64 GB) => 9.277.648.846 bytes (8.64 GB) / 21.322 files in 0.203000

Creating 32 hashing thread(s) with XXH3
001% 00:00:01 (  88.50 MB) of (   8.64 GB)           92.795.037 /sec
010% 00:00:00 (   1.73 GB) of (   8.64 GB)          855.537.805 /sec
020% 00:00:00 (   1.73 GB) of (   8.64 GB)        1.855.537.805 /sec
030% 00:00:00 (   3.46 GB) of (   8.64 GB)        3.711.113.442 /sec
040% 00:00:00 (   3.46 GB) of (   8.64 GB)        3.638.885.713 /sec
050% 00:00:00 (   4.32 GB) of (   8.64 GB)        4.638.885.713 /sec
060% 00:00:00 (   5.18 GB) of (   8.64 GB)        5.566.630.010 /sec
070% 00:00:00 (   6.05 GB) of (   8.64 GB)        6.494.406.987 /sec
080% 00:00:00 (   6.91 GB) of (   8.64 GB)        7.422.174.326 /sec
090% 00:00:00 (   7.78 GB) of (   8.64 GB)        8.349.898.168 /sec
Scanning filesystem time            0.203 s
Data transfer+CPU   time            0.564 s
Data output         time            0.016 s
Total size                      9.277.648.846 (   8.64 GB)
Tested size                     9.277.648.846 (   8.64 GB)
Duplicated size                   254.574.801 ( 242.78 MB)
Duplicated files                        4.033
Worked on 9.277.648.846 bytes avg speed (hashtime) 16.449.731.996 B/s
GLOBAL SHA256: 1866EC617744139BD15D451EE1224AD2DAD64815E92E039F38FAE809DB20C851

0.813 seconds (00:00:00)  (all OK)



P:\>c:\zpaqfranz\zpaqfranz sum c:\dropbox\dropbox -wyhash -all -summary
zpaqfranz v54.10-experimental (HW BLAKE3), SFX64 v52.15, compiled Dec 20 2021

****** WARNING: WYHASH IMPLEMENTATION IS JUST FOR TEST *******

franz:-wyhash -summary
Getting WYHASH ignoring .zfs and :$DATA

Found (8.64 GB) => 9.277.648.846 bytes (8.64 GB) / 21.322 files in 0.188000

Creating 32 hashing thread(s) with WYHASH
001% 00:00:03 (  90.27 MB) of (   8.64 GB)           94.655.567 /sec
010% 00:00:01 ( 900.74 MB) of (   8.64 GB)          944.498.663 /sec
020% 00:00:01 (   1.74 GB) of (   8.64 GB)        1.863.419.072 /sec
040% 00:00:01 (   3.47 GB) of (   8.64 GB)        3.725.789.177 /sec
050% 00:00:00 (   4.33 GB) of (   8.64 GB)        4.653.029.893 /sec
060% 00:00:00 (   5.24 GB) of (   8.64 GB)        5.627.124.447 /sec
070% 00:00:00 (   6.06 GB) of (   8.64 GB)        6.509.157.446 /sec
090% 00:00:00 (   7.79 GB) of (   8.64 GB)        8.359.555.859 /sec
Scanning filesystem time            0.188 s
Data transfer+CPU   time            1.704 s
Data output         time            0.015 s
Total size                      9.277.648.846 (   8.64 GB)
Tested size                     9.277.648.846 (   8.64 GB)
Duplicated size                   254.574.801 ( 242.78 MB)
Duplicated files                        4.033
Worked on 9.277.648.846 bytes avg speed (hashtime) 5.444.629.604 B/s
GLOBAL SHA256: 455D58016668B788995FD0B4F33DFA8B3D87E9023E6AAAAF0C1AF364BF1A283A

1.938 seconds (000:00:01)  (all OK)
```
Not the first, nor the 10th best choice for this scenario, but it's not an issue, it's a feature, after all.
