### ISSUE TITLE
Don't define wyhashmap if WYHASH_32BIT_MUM is set

### ISSUE THREAD

**Issue by rcombs** [wangyi-fudan/wyhash#107]
Setting `WYHASH_32BIT_MUM` to 1 causes the `wy2u0k` function not to be defined, but `wyhashmap` is still defined, and uses `wy2u0k`. This should be behind `#if !WYHASH_32BIT_MUM`, or moved to its own header.

**Comment by wangyi-fudan** [comment]
thanks! I removed the hashmap as people mainly use wyhash for hash function and PRNG
