### ISSUE TITLE
Test vectors

### ISSUE THREAD

**Issue by cocowalla** [wangyi-fudan/wyhash#11]
Any chance you could publish some test vectors for wyhash?

This would be really useful for verifying correctness of ports to other languages.

**Comment by wangyi-fudan** [comment]
Dear Cocowalla:
I am not sure about the meaning of "test vectors". I guess the simplest way to verify a ported code is to run the c version and c# version seperately, and compare them.
thanks!

**Comment by cocowalla** [comment]
Test vectors are _inputs_ along with their _expected outputs_, and are commonly published for ciphers and hashes (although for some reason they seem to be more commonly published for cryptographic hashes, rather than non-cryptographic ones :man_shrugging:).

For example, in the [MD5 RFC](https://tools.ietf.org/html/rfc1321.html) some vectors are included in section A.5, some are published on the [RIPEMD160 website](https://homes.esat.kuleuven.be/~bosselae/ripemd160.html), and NIST [publishes](https://csrc.nist.gov/projects/cryptographic-algorithm-validation-program) test vectors for various algorithms.

I can of course run the C version myself, but it would be really useful to have an authoritative list published here. This might also help, for example, if different results are observed on different processor architectures, or if different compilers produce different results.

**Comment by wangyi-fudan** [comment]
thanks for your comment! I add test vectors in readme

**Comment by eldruin** [comment]
Historically at least the hash results have changed in between revisions. In [my rust implementation of wyhash](https://github.com/eldruin/wyhash-rs) I added [a small program](https://github.com/eldruin/wyhash-rs/tree/master/original) that downloads the reference version of wyhash for my implementation automatically and generates the hashes and RNG for a list of inputs, which I later use in my tests.

**Comment by cocowalla** [comment]
@eldruin I had come across your rust port, but hadn't seen this test utility, so thanks for the pointer :smile:

**Comment by Sahnvour** [comment]
Looks like they're gone, would you mind putting them back ?
I guess that the version 2 of wyhash also changed their results.
