### ISSUE TITLE
How do you pronounce wyhash?

### ISSUE THREAD

**Issue by tansy** [wangyi-fudan/wyhash#116]
It's not a real issue, more of a discussion. Question is - how do you pronounce wyhash? Preferably in [IPA](https://en.wiktionary.org/wiki/Wiktionary:IPA_pronunciation_key). [wi hæʃ] or [waɪ hæʃ]?

Just for the record.

**Comment by wangyi-fudan** [comment]
I call it " ˈdəbəl yo͞o wai  hæʃ".  But it is just my internal pronunciation as a non-native speaker. Feel free for pronounce it in your own way. wyhash is not a standard, but an effort.

**Comment by tansy** [comment]
That's more like spelling. My question was how you pronounce it "originally", or how you imagine/d it in first place?
