### ISSUE TITLE
Error in line 15 of test_vector.cpp

### ISSUE THREAD

**Issue by Exaelitus** [wangyi-fudan/wyhash#117]
There is a comma missing at the end of line 15, so the 7th and 8th items are actually merged.  This is why etalons_v looks like it has one less vector than msgs_v

The correction should be a comma at the end of line 15, then maybe add the merged msg from the bug as a 9th item.  Or perhaps merge the 7th and 8th items as the new 7th item, and add the previous 7/8 items as the 9th:

    vector<string> msgs_v = {
 ...
        "12345678901234567890123456789012345678901234567890123456789012345678901234567890",
       "1234567890123456789012345678901234567890123456789012345678901234567890",
        "1234567890"
    };

Then add the correct expects in etalons_v

**Comment by Exaelitus** [comment]
Also, (I know this is potentially a new issue if true, but I don't have any way to verify if it is really an issue ) All the vectors are failing when I test them : 

1!BB:   [8]"0x0000000000000000" =/=     [8]"0x42bc986dc5eec4d3"
2!BB:   [8]"0xc7400fc7d3902875" =/=     [8]"0x84508dc903c31551"
3!BB:   [8]"0x769b6466e4c5a891" =/=     [8]"0x0bc54887cfc9ecb1"
4!BB:   [8]"0x1ba63ecc21d10415" =/=     [8]"0x6e2ff3298208a67c"
5!BB:   [8]"0x19662436ddb11e89" =/=     [8]"0x9a64e42e897195b9"
6!BB:   [8]"0x5e3e9b34fbbe6655" =/=     [8]"0x9199383239c32554"
7!BB:   [8]"0x31a0f8808291c38d" =/=     [8]"0x7c1ccf6bba30f5a5"

( The first 8-byte hex value is the hash from wyhash() and the second value is what is in test_vector.cpp )

**Comment by wangyi-fudan** [comment]
fixed. Thanks!
