### ISSUE TITLE
Any safe sentinel values?

### ISSUE THREAD

**Issue by rtfeldman** [wangyi-fudan/wyhash#118]
Thank you for making wyhash!

I couldn't find any documentation one way or the other on this, so I thought I'd ask: are there any numbers that wyhash is guaranteed never to return?

I'm trying to figure out if there are any values that would be safe to use as sentinel values. For example, if I knew for sure that wyhash would never return all zeroes, no matter the input, then I could use 0 as a sentinel value.

Thanks again!

**Comment by wangyi-fudan** [comment]
wyhash behaves like (determinstic) ramdom number generators. I guess no safe values, especially with different seed and secrets

**Comment by rtfeldman** [comment]
Got it, thank you!
