### ISSUE TITLE
wyrand interface change

### ISSUE THREAD

**Issue by oertl** [wangyi-fudan/wyhash#12]
Is there any reason why the interface of wyrand was changed to
 https://github.com/wangyi-fudan/wyhash/blob/05d803d3e8cbb656639c27636258e8b74fe8c3d4/wyhash.h#L72
? I prefered the old interface of version 1:
https://github.com/wangyi-fudan/wyhash/blob/e1e1b50cc7067504f42f81062739ec3b57dd97da/wyhash.h#L69
which does not rely on a single global state. Otherwise, it is difficult to create two independent streams of pseudo-random numbers.

**Comment by wangyi-fudan** [comment]
deaar oertl:
yes, I am also balancing the two methods. 
Because, in real coding, use this new version simplfies coding.
However, the old version is more general. 
OK, let's try to keep them all :-)
