### ISSUE TITLE
Version final 4 cannot be applied to data streams

### ISSUE THREAD

**Issue by oertl** [wangyi-fudan/wyhash#121]
Thank you very much for your continued work on wyhash! Version final 4 (https://github.com/wangyi-fudan/wyhash/commit/c46ecdc24559e87e22ff9a9ba2161e7a1403cb3d) requires the length of the input at the beginning, which prevents this algorithm from being applied to data streams. Is there a solution that fixes the BadSeeds and PerlinNoiseAV tests without requiring the length upfront?

**Comment by wangyi-fudan** [comment]
Easy and done :-) Thank you for your advice.
