### ISSUE TITLE
WyRand fails 64-bit 1-dimensional collision tests

### ISSUE THREAD

**Issue by vigna** [wangyi-fudan/wyhash#130]
I'm testing this version of WyRand:
```
uint64_t next() {
	x += 0xa0761d6478bd642f;
	const __uint128_t t = (__uint128_t)(x ^ 0xe7037ed1a0b428db) * x;
	return	(t >> 64) ^ t;
}
```

It fails very badly a collision test on its output. That is, it emits much more repeated values than it should (collision is the most basic test—in fact, it is the first test described by Knuth).

The test can be run in a few hours on a good laptop—it is a collision test on 8 billion outputs repeated for 200 times. The expected number of collisions is 346.944, the the actual number is 765, giving a p-value of 1.89588e-83.

[wyrand-coll-0-18446744073709551616-1-8000000000-200-0.txt](https://github.com/wangyi-fudan/wyhash/files/10918372/wyrand-coll-0-18446744073709551616-1-8000000000-200-0.txt)

If you're interested in replicating the failure I can send you the code. The test it self is pretty elementary—generate values, sort them, count the number of repeated values and generate a p-value.

**Comment by wangyi-fudan** [comment]
Hi,
It is already known that wyhash and wyrand fails 64-bit collision test with large number of items. See xxhash page and flyingmutant page.
The xxhash page concludes that wyhash is of 62-bit strength against collisions. wyrand should be similar, say about 62 bit strength.
The BigCrush tests are testing 32 bit PRNG, so wyrand did pass that.
In one word, we should claim only 62 bit strength.

**Comment by vigna** [comment]
Note that testing of hash functions and PRNGs is very different. The meaning of "collision" is entirely different in the two settings.

I'm sorry but looking around I can find only tests about hash functions, not tests about the PRNG. Could you please give me a precise reference (a link) to a PRNG statistical collision test applied to WyRand?

BigCrush's parameters were designed 20 years ago. They are absolutely insufficient for any modern PRNG.

Also, I do not understand what you mean by 62-bit strength in the context of PRNGs. That the upper 62 bits have the number of collisions? The lower 62 bits?

**Comment by wangyi-fudan** [comment]
wyrand passed BigCrush and Practrand from this repo: https://github.com/lemire/testingRNG
The 62 or 63 bits strength instead of ideal 64 bits strength may due to some mathematical limitation hidden in MUM function. It is not the head/tail bits but "steals one bits from all possible bits". 
So the take away message is wyhash and wyrand still works well in practice with 62/63 bits claim.

**Comment by vigna** [comment]
Yes, but I asked you a reference to a *failed* test because you said in your first answer that it is known that it fails collisions tests. PractRand performs no collision tests. BigCrush only performs very small-scale collision test. So these tests have nothing to do with the test failures I've sent you. It is perfectly normal that PractRand and BigCrush gave you no problems. But having a good PRNG goes beyond that. WyRand fails mid-size collisions tests.

You also did not explain what it means "62 bits" for a PRNG. That might have a meaning for hash function, but it does not have any meaning for a PRNG.

So the take away message is that WyRand fails a basic statistical test on about 2TB of data. It should not be used as a PRNG except when very low statistical quality is acceptable.

**Comment by wangyi-fudan** [comment]
flyingmutant did birthday test. It is here, but not openable in China: https://gist.github.com/flyingmutant/cb69e96872023f9f580868e746d1128a

xxhash discussed 62 bit problem here: https://github.com/Cyan4973/xxHash/issues/236

**Comment by wangyi-fudan** [comment]
A 63 bit PRNG is not of low quality.
Suppose you want to generate random number in [0,N]. when N is less than 2^63, wyrand works perfectly for you.
It just not of 64 bits capacity, but 63 bit.

**Comment by vigna** [comment]
You are clearly not understanding what I'm saying. But it is easy to show that your last claim is false.

- The same collision test on the lower 63 bits gives p=9.05405e-44 [wyrand-coll-1-9223372036854775808-1-8000000000-200-0.txt](https://github.com/wangyi-fudan/wyhash/files/10925125/wyrand-coll-1-9223372036854775808-1-8000000000-200-0.txt).
- The same collision test using 2^63 cells, that is, using only the upper 63 bits, gives p=1.98245e-49 
[wyrand-coll-0-9223372036854775808-1-8000000000-200-0.txt](https://github.com/wangyi-fudan/wyhash/files/10925142/wyrand-coll-0-9223372036854775808-1-8000000000-200-0.txt).

So extracting numbers less than 2^63, either upper or lower, will give too many collisions still.

It's nothing dramatic—a 64-bit generator with 64 bits of states can either emit all possible values (like SplitMix64), and it will fail because there are no collisions, or it can decide to emit only a subset of all possible 64-bit integers (which someone might consider a problem, BTW), in which case it has a chance of passing a collision test of this kind.

Your generator however does not pass the test, even restricting to 63 bits. It's more than 11TiB of data, so it's a quite tough test. Users should be aware of the problem, though.

**Comment by avaneev** [comment]
Hi! I'm a competing developer and your reference to "collision tests" in PRNGs is interesting. What is meant by collision test in case of PRNG? What is the theoretical basis for measuring PRNGs for "collisions"? In general, PRNG tests are a bit of "statistical forgery" IMO, because no accepted "uniform randomness" theory exists.

**Comment by avaneev** [comment]
On the other hand, authors of xxhash have found out that wyhash has collision problems as is, so this may be related to your "collision test". Anyway, I'm interested to know theoretical basis for the test.

**Comment by vigna** [comment]
If you're a competing developer I strongly suggest you read the parts about randomness in Knuth's "The Art of Computer Programming". Besides a theory of uniform randomness (the one you claim does not exist), the first practical test he suggests is the collision test. It is one of the most important tests for randomness. You can also read about the collision test in the "long guide" of the TestU01 framework for random testing.

**Comment by avaneev** [comment]
@vigna Please tell me the page numbers where the "theory" is provided. "The Art of Computer Programming" has many volumes and pages. Uniformity does assume absence of collisions, but I'm interested to know bounds of this test. You seem to treat the bounds rather freely.

**Comment by avaneev** [comment]
@vigna I've found this excerpt from Knuth's book: https://www.informit.com/articles/article.aspx?p=2221790 Specifically: "There are several ways to formulate decent abstract definitions of randomness". Which one is the prevailing "theory"? Knuth's own text only deals with "uniform probability" of drawing a specific number. But tests like PractRand are much more complex than that definition.

**Comment by avaneev** [comment]
@vigna For example, Knuth states "Thus, if we are choosing a million digits at random and if the first 999,999 of them happen to come out to be zero, the chance that the final digit is zero is..." This is a fundamentally flawed proposition, because PRNG can't produce a train of 999,999 zeroes - such sequence won't pass statistical tests. There are obvious bounds to uniform randomness exist. Knuth's source of mistake stems from basic linear "uniform probability of drawing a number" consideration.

**Comment by vigna** [comment]
Well I guess you should write him and explain him his big mistake. 🤷🏻‍♂️

**Comment by reinerp** [comment]
There's a simple theoretical reason that the collision tests are failing here, independent of the small state size: WyRand's output filter has a certain symmetry.

WyRand's output filter is this:

```
uin64_t output_filter(uint64_t x) {
  const __uint128_t t = (__uint128_t)(x ^ 0xe7037ed1a0b428db) * x;
  return (t >> 64) ^ t;
}
```

This has the following symmetry: `output_filter(x) = output_filter(x ^ 0xe7037ed1a0b428db)`. This symmetry implies that the output filter can cover at most 50% of the output space, which is too little: a _random_ output filter should cover ~63% of the output space (1 - 1/e), see https://claude.ai/share/ca849d14-0b5e-4b54-bdea-d56e8e79e7ec. 

It seems worth trying to break this symmetry. One simple way I came up with is to perform an addition on the RHS of the multiplication:

```
uin64_t output_filter_asymmetric(uint64_t x) {
  const __uint128_t t = (__uint128_t)(x ^ 0xe7037ed1a0b428db) * (x + 0xa0761d6478bd642f);
  return (t >> 64) ^ t;
}
```

This particular choice of additive constant (namely: the same one as used to step the Weyl sequence) means that the overall step function can be the same number of instructions as before:

```
uint64_t next_asymmetric() {
	uint64_t y = x;
	x += 0xa0761d6478bd642f;
	const __uint128_t t = (__uint128_t)(y ^ 0xe7037ed1a0b428db) * x;
	return (t >> 64) ^ t;
}
```

I haven't run any statistical tests on this, but it seems plausible that this step function could improve the outcome on collision tests.

[Side note: small state size necessarily breaks collision tests when the output filter is bijective, but when the output filter is non-bijective it might not. For example, a 64-bit counter with a SHA256 output filter would presumably pass collision tests all the way up to 2^64 samples.]

**Comment by reinerp** [comment]
I ran the asymmetric version of WyRand from above under both BigCrush and a collision test similar to what @vigna described. Specifically: I ran TestU01's `sknuth_Collision` with N=200, n=8000000000, d=2^32, t=2, with some fixes for integer overflow that occurred with k=2^64. WyRand passes BigCrush and fails the bigger collision test; the asymmetrized version passes both BigCrush and the bigger collision test.

**Comment by reinerp** [comment]
@vigna do you have a recommendation on configurations (or styles of configurations) of other collision tests to try on this asymmetric variant of WyRand?

**Comment by vigna** [comment]
I'm confused. You ran a test on 2-tuples of top 32 bits instead of on the output. Why did you expect it would fail? It's a different test. I'd start with replicating the original test.

Also, TestU01 does not support more than around 2 billion points (that's when it finishes the primes in its hash tables). How did you manage to make 8 billion points work? Did you rewrite `sknuth_Collision`?

**Comment by vigna** [comment]
> [Side note: small state size necessarily breaks collision tests when the output filter is bijective, but when the output filter is non-bijective it might not. For example, a 64-bit counter with a SHA256 output filter would presumably pass collision tests all the way up to 2^64 samples.]

Well, it depends on how the test is sized. The maximum stringency for the collision test happens at points ≈1.25 cells. In this case it means that you'd complete the orbit. Even assuming that you completed the orbit with a reasonable *p*-value, as soon as you wrap all points are collisions and the *p*-value goes to zero almost instantly (you can upper bound it analytically).

What is true is that if you mix in the right way you can probably fool the test for so much that you can consider a possible failure irrelevant (I mean, you'll never enumerate the orbit). The modification you propose appears to be an enormous improvement—for this version the bias probably can't be caught by a test.

**Comment by reinerp** [comment]
> I'm confused. You ran a test on 2-tuples of top 32 bits instead of on the output. Why did you expect it would fail? It's a different test. I'd start with replicating the original test.

Sorry, I should clarify. TestU01 operates on 32-bit numbers, not 64-bit numbers. For a 64-bit RNG like WyRand, we present the high and low halves as two consecutive 32-bit outputs. The 2-tuples then reassemble the original 64-bit numbers. It's convoluted, but it was the most expedient way I could build it out of existing TestU01 code.

As a cross-check I made sure I could reproduce WyRand's failure. I did. Then I confirmed that under the same test, the asymmetrized variant of WyRand passed.

As an alternative I could build a new collision test from scratch. Perhaps I should do that. But if you have an optimized implementation available already, would you be willing to share?

> Also, TestU01 does not support more than around 2 billion points (that's when it finishes the primes in its hash tables). How did you manage to make 8 billion points work? Did you rewrite sknuth_Collision?

I have a private fork of TestU01 in which I've done many speed optimizations (while testing to preserve bit-identical results), including removing virtual function calls from inner loops and supporting parallelization for generators that support seeking. Among other things I changed the collision test implementation from hash-table-based to radix-sort-based. That, plus one or two changes to use larger integer types, supported a much larger set of points.

**Comment by vigna** [comment]
Well, you're right. I've been playing with this code for five years, first in C++ then in Rust... maybe it's time to make it public. If I wait to have it perfect I'll never release it!

[Please have a look](https://github.com/vigna/coll-birth-rs). Comments are welcome!

**Comment by reinerp** [comment]
Thank you, this test suite is great -- very fast and powerful!
