### ISSUE TITLE
Full round for every multiple 48-bytes, including last one

### ISSUE THREAD

**Issue by tansy** [wangyi-fudan/wyhash#137]
Full round for every 48-bytes multiple, including last one.

Reason why wyhash cannot by made "streamable" is that it uses procedure for incomplete round for last full (48 bytes) round instead of full round procedure. This way every time you receive 48 bytes you don't know whether you can process it or not because, if is the last 48 bytes it will be processed differently than if it's not.
So I thought it would be good to change it to less ambiguous version and treat every full round of 48 bytes the same, rather than different. As noticed in streaming issue #131 it needs to change simple test from greater to greater or equal in [line 127](https://github.com/wangyi-fudan/wyhash/blob/ea3b25e1aef55d90f707c3a292eeb9162e2615d8/wyhash.h#file-wyhash-h-L127) and [line 134](https://github.com/wangyi-fudan/wyhash/blob/ea3b25e1aef55d90f707c3a292eeb9162e2615d8/wyhash.h#file-wyhash-h-L134).

```
--- wyhash.h~	2023-09-29 21:20:42.000000000 +0000
+++ wyhash.h	2023-09-29 21:46:46.000000000 +0000
@@ -124,14 +124,14 @@ static inline uint64_t wyhash(const void
   }
   else{
     size_t i=len; 
-    if(_unlikely_(i>48)){
+    if(_unlikely_(i>=48)){
       uint64_t see1=seed, see2=seed;
       do{
         seed=_wymix(_wyr8(p)^secret[1],_wyr8(p+8)^seed);
         see1=_wymix(_wyr8(p+16)^secret[2],_wyr8(p+24)^see1);
         see2=_wymix(_wyr8(p+32)^secret[3],_wyr8(p+40)^see2);
         p+=48; i-=48;
-      }while(_likely_(i>48));
+      } while(_likely_(i>=48));
       seed^=see1^see2;
     }
     while(_unlikely_(i>16)){  seed=_wymix(_wyr8(p)^secret[1],_wyr8(p+8)^seed);  i-=16; p+=16;  }
```

I decided to test the idea and change it, and test the results.

I did extensive test and the results are this:
- resulting hash will not change except multiple of 48 bytes (i.e. 48, 96, 144 and so on)
- it doesn't change wyrand in any way
- [rurban/smhasher](https://github.com/rurban/smhasher) tests, including extra 384/768/1536 bits to cover and test multiple of 48 bytes, especially, come out identical to current version.
- practrand tests come out identical to current version

There are other tests that can be done as well. The best one would be [xxhash collision test](https://github.com/Cyan4973/xxHash/tree/dev/tests/collisions). It gives number of collisions for given hash. It requires huge amounts of RAM though. _Assuming N p-bit hashes the expected number of colliding pairs is `N(N-1)/(2*2^p)`_ ([link](https://github.com/Cyan4973/xxHash/issues/753#issuecomment-1298335409)). So, for 10G of hashes (80GB of RAM) it is expected to get 2.7 collisions, 15G of hashes (120GB of RAM) would give 6.1 collisions. Cyan [considers](https://github.com/Cyan4973/xxHash/issues/753#issuecomment-1298620586) _25GB of hashes to be a reasonable quantity_. That would give expected 16.9 collisions.
If one can't afford that amount, there is a _--filter_ mode which reduces the amount of memory needed by a factor ~4, though it's also sensibly slower ([link](https://github.com/Cyan4973/xxHash/issues/753#issuecomment-1298620586)).
There is a general wyhash patch for collision tester attached to the post if anyone was interested in testing it.

I procured other kind of test. I used hash of multiple of 48 zeroed bytes and processed it with practrand. In 500k these hashes it processed 24 TB of data that are the most challenging to hash - zeroed, "repetitive" strings. In this test it shown two anomalies; in comparison current version shown one anomaly, right at the start.

Logs and programs, and diffs are included in tarball [here](https://files.fm/f/hbsyna72g7).

If tests prove successful perhaps you would consider making such change. It would help to adapt has for a different application.

[xxHash-dev-wyhash-test.diff.gz](https://github.com/wangyi-fudan/wyhash/files/12772924/xxHash-dev-wyhash-test.diff.gz)

**Comment by wangyi-fudan** [comment]
many thanks! I will update it.
