### ISSUE TITLE
Use fixed width integer types instead of unsigned long long

### ISSUE THREAD

**Issue by oertl** [wangyi-fudan/wyhash#14]
`unsigned long long` has at least 64 bits and really has 64 bits on most platforms. However, it is possible that it has more than 64 bits on some platforms. Therefore, it would be better to replace unsigned long long by uint64_t which is defined since C99 (see https://en.cppreference.com/w/c/types/integer). Otherwise, wyhash would behave unexpectedly on exotic platforms that implement unsigned long long with more than 64 bits.

**Comment by wangyi-fudan** [comment]
Dear oertl:
previously, I use <stdint.h> and uint64_t. However, someone tell me that <stdint.h> is not portable( https://github.com/rurban/smhasher/issues/53 ). So I roll back to unsigned long long... I am not expertized in the portability field, may be we need to discuss it further.

**Comment by lemire** [comment]
It is standard compliant and portable but it requires a recent compiler (C++11). It works with all up-to-date C++ compilers. However, some people stick with compilers for 20 years ago.

**Comment by wangyi-fudan** [comment]
Thanks for both discussions. For both safety reason and standardization reason, I decide to use stdint.h. wyhash is designed for the future, not the past.

**Comment by lemire** [comment]
I have personally moved all my software work to `C99` and `C++11` or better. This causes some difficulties for people who have old systems, but I think it is worth it.

It is hard for beginners to know what `long long` means.
