### ISSUE TITLE
major/fundamental: probability of fatal entropy loss.

### ISSUE THREAD

**Issue by leo-yuriev** [wangyi-fudan/wyhash#15]
Well, it was obvious from the beginning.
However, I did not see that this issue was voiced and/or discussed somewhere.
I assume that not all users can see this drawback, respectively, can be misled and make a decision without realizing all the risks.
So I decided to raise this issue (better late than never).

---

From the source code make it clear that wyhash uses problematic "Narrow-pipe" [Merkle–Damgård construction](https://en.wikipedia.org/wiki/Merkle%E2%80%93Damg%C3%A5rd_construction) with the MUL-XOR mixer as an entropy sponge.

```
static inline uint64_t wyhash(const void *key, uint64_t len, uint64_t seed) {
  const uint8_t *p = (const uint8_t *)key;
  uint64_t i;
  for (i = 0; i + 32 <= len; i += 32, p += 32)
    seed = _wymum(seed ^ _wyp0,
                  _wymum(_wyr64(p) ^ _wyp1, _wyr64(p + 8) ^ _wyp2) ^
                      _wymum(_wyr64(p + 16) ^ _wyp3, _wyr64(p + 24) ^ _wyp4));
  seed ^= _wyp0;
  switch (len & 31) {
  case 1:
  /* ... omitted for brevity ... */
  case 30:
    seed = _wymum(__wyr64(p) ^ seed, __wyr64(p + 8) ^ _wyp2) ^
           _wymum(__wyr64(p + 16) ^ seed,
                  ((_wyr32(p + 24) << 16) | _wyr16(p + 24 + 4)) ^ _wyp4);
    break;
  case 31:
    seed = _wymum(__wyr64(p) ^ seed, __wyr64(p + 8) ^ _wyp2) ^
           _wymum(__wyr64(p + 16) ^ seed,
                  ((_wyr32(p + 24) << 24) | (_wyr16(p + 24 + 4) << 8) |
                   _wyr08(p + 24 + 6)) ^
                      _wyp4);
    break;
  }
  return _wymum(seed, len ^ _wyp5);
}
```
The problem here is that if one multiplier equals zero, then the result is independent of the other multiplier.

Therefore, some individual 64-bit words and/or on any initial part of the processed data may not affects the hashing result.
The probability of such cases cannot be called large, but it increases in proportion to the size of the data.

In my opinion, this is unacceptable for a universal/common hash function. However, in some cases where the kind of the data is known (e.g. for ascii texts), you can be sure that no problems will occur.

So I think you need to clearly describe this defect.

For instance the test case:
```
#include <cinttypes>
#include <cstdint>
#include <cstdio>
#include <cstdlib>

#include "wyhash.h"

int main(int argc, const char *argv[]) {
  const unsigned N = 128;
  uint64_t array[N];
  static_assert(N > 4, "precondition");

  const unsigned offset = 4;
  static_assert(offset % 4 == 0 && offset < N, "precondition");

  memset(array, 'x', sizeof(array));
  array[N - 4] = UINT64_C(0xe7037ed1a0b428db);
  array[N - 1] = UINT64_C(0x1d8e4e27c47d124f);

  array[0] = 0;
  const uint64_t A = wyhash(array, sizeof(array), 42);
  printf("wyhash(%" PRIx64 ", xxx, poison, xxx) = %" PRIx64 "\n", array[0], A);

  array[0] = 1;
  const uint64_t B = wyhash(array, sizeof(array), 42);
  printf("wyhash(%" PRIx64 ", xxx, poison, xxx) = %" PRIx64 "\n", array[0], B);

  array[0] = 2;
  array[N - 3] = 'Y';
  const uint64_t C = wyhash(array, sizeof(array), 42);
  printf("wyhash(%" PRIx64 ", xxx, poison, Yxx) = %" PRIx64 "\n", array[0], C);

  return (A != B && B != C && A != C) ? EXIT_SUCCESS : EXIT_FAILURE;
}
```

Output:
```
wyhash(0, xxx, poison, xxx) = d1fb6b2bf52fd8db
wyhash(1, xxx, poison, xxx) = d1fb6b2bf52fd8db
wyhash(2, xxx, poison, Yxx) = d1fb6b2bf52fd8db
```

**Comment by wangyi-fudan** [comment]
Dear yuriev:
I appriciate your discussion. Yes, I confirm this problem. I have two thoughts:
1: wyhash is designed to be as fast as possible, not for security. in my basic operator _wymum(A^p1,B^p2), if A is set to p1 then wyhash is not dependent on B. However, this occurs with 2^-64 probability in natural data which can be almost ignored. When being intendly attacked wyhash surely break as you said (by setting some parameter to magic numbers).
2: We can develop some secure version of hash function at the cost of speed. for example, _wymum(A^p1,B^p2) ^ _wymum(A^p3,B^p4) . I will try this direction.
Let's togather build a ultimate hash function!

**Comment by wangyi-fudan** [comment]
Dear yuriev:
I am happy to say we have a hot fix for this problem.
The key problem _wymum(A^p1,B,p2) is insecure. It can be attacked and zeroed by setting A to p1 or B to p2.
My candidate solution is update this mix function to _wymum(A^seed^p1, B^seed^p2). If the user initialize  seed in a private way, the attackers can not construct simple attack. 
I wrote a v2draft. See if you are satisfied on it. The speed is not compromised.

**Comment by leo-yuriev** [comment]
@wangyi-fudan, your improvements are (most likely) useful, however I would recommend alternating ADD and XOR operations.

Nevertheless, I would still like to draw attention to the fundamental/unavoidable problems in the "narrow pipe" construction, especially when multiplication is used as a compression mixer/function:
 - "narrow pipe" prone to accumulate shortcomings of the basic hash function, so it requires to use an "ideal" compression function.
 - WideMUL-XOR (aka MUM, designed by @vnmakarov) mixer is nonlinear, but it has a "narrow mapping" property, i.e. produces non-uniform distribution. Therefore MUM within "narrow pipe" will be lose some bit of entropy on each step.
 - when using direct multiplication to mix data with the internal state in "narrow pipe", there is always the possibility that the data will contain poison, which will cause all the accumulated entropy to be lost (i.e. the result will not depend on previous data).

I don't think you need to fix all these flaws because this means you will just create a new hash function. However, users should be warned about the issue under discussion. What exactly to do - should be your decision.

---

Besides, wyrand() is also of some concern.

Briefly, it accepts any 64-bit value as a seed. Therefore, it should be analytically (since there is no other way) proven that the generator period is 2^64.

Otherwise, with some custom seed, the generator can get into a unacceptably short ring. Alternatively, it is sufficient to prove that the generator has no rings shorter than some acceptable period (i.e. 2^48).

**Comment by leo-yuriev** [comment]
[_copy & paste for the correctness_](https://github.com/lemire/SwiftWyhash/issues/10#issuecomment-500673988)

I reformatted the code and looked it up.
```
static inline uint64_t wyrand(uint64_t *seed) {
  *seed += _wyp0;
  return _wymum(*seed ^ _wyp1, *seed);
}
```
It is obvious that the period is 2^64, since _wyp0 == 11562461410679940143 (0xa0761d6478bd642f) is prime.

Don't know where I was looking the first time, but my suspicions are completely unreasonable.
@wangyi-fudan, please excuse my inattention.
