### ISSUE TITLE
wyhash paper

### ISSUE THREAD

**Issue by wangyi-fudan** [wangyi-fudan/wyhash#17]
My dear friends:
  I feel almost satisfied with current maturity of wyhash. Maybe it's time to write an "immortal" paper. I need your help on history review/technical words/tables/language editing etc. I bravely imagine that this can be achieved on Github. Join me to be an author freely!
  Many thanks!
Yours,
Yi

**Comment by lemire** [comment]
I can help with an academic paper if you’d like. Email me if you’d like to discuss.

**Comment by wangyi-fudan** [comment]
Yes, let's work by editing manuscript.md.

**Comment by eldruin** [comment]
Please let me know if you would like to add some notes about the [Rust implementation of wyhash](https://github.com/eldruin/wyhash-rs).

**Comment by wangyi-fudan** [comment]
I designed a section call "language bindings". perhaps you could give some notes there.

**Comment by lemire** [comment]
For an academic paper, editing manuscript.md is probably not the best path forward. I would recommend setting up a project on overleaf. But there are also preconditions: one should target a venue and then determine the work that is needed to reach the standards of the venue.

If all you want is to informally document the approach, then manuscript.md is fine, but for a science paper, I recommend a more formal approach.

Cheers!

**Comment by wangyi-fudan** [comment]
My idea is to do multi-user editing on manuscript.md and finally I will convert it to a word document and submit it to some journal.  It is a first trial to do such paper :-)

**Comment by wangyi-fudan** [comment]
The paper barebones is almost there with tables and benchmark supporting information. I feel strenuous to handle large text as it is not like source code. Please help me to improve it piece by piece.
Many thanks!

**Comment by wangyi-fudan** [comment]
The manuscript draft is online and was send to my supervisor. My dream is publishing it on Science or PNAS, please don't laugh at me :-)  Help needed!
