### ISSUE TITLE
Use Yves tests as they're stricter/better than smhasher

### ISSUE THREAD

**Issue by dumblob** [wangyi-fudan/wyhash#24]
See https://github.com/rurban/smhasher/issues/31 .

**Comment by paulie-g** [comment]
I have added wyhash to my private fork of Yves' SMHasher, found an avalanche test failure and submitted a PR at #25 

Running the full suite now, will update with results.

**Comment by wangyi-fudan** [comment]
many thanks!
I update wyhash. And I will rum Yves test by myself.

**Comment by paulie-g** [comment]
As an FYI, my fork of wyhash with my patch passes Yves' SMhasher in full.
