### ISSUE TITLE
wyrand(void) and wyrand(uint64_t) conflict

### ISSUE THREAD

**Issue by paulie-g** [wangyi-fudan/wyhash#27]
I understand this might be a v1 to v2 change (#12). In any case, if you want to keep both available, either a name change or an ifdef/else around them is in order.

**Comment by wangyi-fudan** [comment]
ah, this bug is just because I am a c++ guy...

**Comment by paulie-g** [comment]
I knew there was something wrong with you ;) I didn't submit a PR this time because I didn't know how you wanted to handle it.

**Comment by wangyi-fudan** [comment]
done
