### ISSUE TITLE
wyhash is slower than other popular hash functions for large enough key size in my performance benchmarks

### ISSUE THREAD

**Issue by hungptit** [wangyi-fudan/wyhash#30]
I add wyhash hash function into [my benchmark](https://github.com/hungptit/AquaHash/blob/master/benchmark/random_string.cpp) and below are my observations:

1. myhash is the fastest for the key sizes from 1-3 bytes
2. std::hash is faster than wyhash for the key size from 4-31 bytes.
3. [AquaHash](https://github.com/hungptit/AquaHash/blob/master/benchmark.md) is the fastest hash function for key size > 31 bytes
4. clhash, created by @lemire, outperforms wyhash if the key sizes are divisible by 8. clhash is an excellent candidate if the data size is >= 96 bytes 
5. The maximum bytes/cycle rate of wyhash is about 6 bytes/cycle and it is slower than all studied hash functions except boost::hash
6. xxhash64, created by @Cyan4973, is the best in term of usability i.e it provides the update function and is very easy to use, portability (support all OSes), and performant i.e the maximum rate is 7.5 bytes/cycle.

My results might be biased, however, you can always run the benchmark in your machine using steps described from this page https://github.com/hungptit/AquaHash/blob/master/benchmark.md.

![short_strings](https://user-images.githubusercontent.com/399240/62916453-5fdd9780-bd4d-11e9-9664-ba9901e4d54e.png)
![large_strings](https://user-images.githubusercontent.com/399240/62916460-6b30c300-bd4d-11e9-8e43-8a73f1755bec.png)
![bytes-per-cycle](https://user-images.githubusercontent.com/399240/62916575-d5e1fe80-bd4d-11e9-8312-f2362f60f743.png)

**Comment by wangyi-fudan** [comment]
wyhash is intended for short string hashing, eg. hash table. To hash large chunk, please choose other hash functions. wyhash also have some security consideration which make it slower. Other popular hash function MAY either suffer from quality issue (see SMHasher) or even security issue.

**Comment by hungptit** [comment]
IMO, wyhash is an excellent portable solution in term of performance and quality for small key size i.e < 192 bytes. I think you should mention it in the README to avoid confusion or misuse.
