### ISSUE TITLE
Wyhash is used in Zig language

### ISSUE THREAD

**Issue by data-man** [wangyi-fudan/wyhash#31]
[wyhash.zig](https://github.com/ziglang/zig/blob/master/lib/std/hash/wyhash.zig)

Currently wyhash is a hasher by default in a hash table.
IMHO this can be mentioned in readme.

Thank you!

**Comment by wangyi-fudan** [comment]
OK! thanks！

**Comment by data-man** [comment]
Please change zig to Zig. :)
