### ISSUE TITLE
Commit messages [suggestion]

### ISSUE THREAD

**Issue by cocowalla** [wangyi-fudan/wyhash#34]
Hi Yi, again thanks for wyhash and wyrand! :pray: 

I'm watching this repo, to keep abreast of what your doing, and with an eye on updating my C# port to include wyhash v2 and v3 once they've stabilised.

I have a polite suggestion to propose :smile: Most of your git commit messages are very generic, such as "Update wyhash.h", or "Add files via upload", and these make it a bit difficult to follow your changes. My suggestion is to use more specific commit messages than explain what has been changed, such as you did [here](https://github.com/wangyi-fudan/wyhash/commit/063144833970551aa2c2e017f11e6bdbd35834a6).

It is of course but a suggestion - feel free to ignore it :slightly_smiling_face:

**Comment by wangyi-fudan** [comment]
many thanks for your watching. most of time , I am lonely, just persueing the speed. I will make update a bit clear :-)
