### ISSUE TITLE
Wyhash v3 is not optimal for stream processing

### ISSUE THREAD

**Issue by oertl** [wangyi-fudan/wyhash#35]
Unlike the first two versions, the third version of Wyhash is not optimal for stream processing. After Wyhash v1 and v2 received a chunk of 32 bytes, they were able to process it immediately. Wyhash v3 must wait for the next byte to decide how to process the previous 32 bytes. This is because the last 32 bytes are processed by the main loop when they are not at the end of the stream. Otherwise, they are processed within the finalization step that does not match the main loop. As a result, a streaming version of Wyhash v3 will be more complex than those of v1 and v2.

**Comment by wangyi-fudan** [comment]
thanks! I will try to improve it next week, though I am writing the paper. I just want to be perfect.

**Comment by wangyi-fudan** [comment]
done. Is it OK?

**Comment by oertl** [comment]
Looks good, thanks!
