### ISSUE TITLE
Trivial DoS collision for hash combiners

### ISSUE THREAD

**Issue by ivte-ms** [wangyi-fudan/wyhash#37]
Somewhat related to the previous issue: https://github.com/wangyi-fudan/wyhash/issues/36

Imagine any code that combines hashes with wyhash64:

```
uint64_t getUserHash(const User& user) {
  auto h0 = hash(user.firstName.data(), user.firstName.size(), 0);
  auto h1 = hash(user.lastName.data(), user.lastName.size(), h0);
  auto h2 = hash(user.company.data(), user.company.size(), h1);
  return wyhash64(h2, user.phoneNumber);
  // or
  // return wyhash64(user.phoneNumber, h2);
}
```
If an adversary can control this field, all they have to do is to write _wyp0 (for the first variation) or _wyp1 (for the second variation) there to make getUserHash always return 0 regardless of the value of the other data (because `_wyp0 ^ _wyp0` is 0, and multiplying by 0 returns 0).

wyhash64(EvilConstant, input) should be a good hash for any value of EvilConstant.
The same is true for wyhash64(input, EvilConstant).

I understand that wyhash is not a crypto hash, but this is probably not a very difficult thing to fix, and it directly affects the quality of the hash.

**Comment by wangyi-fudan** [comment]
ah, this is related to previous one (https://github.com/wangyi-fudan/wyhash/issues/15). I will explain it here:
The version 1 wyhash is vulnerable to evilconstant. After issue15, version 2 and 3 use seed as a mask to protect/hide the constants. So if you keep the seed as a secrete (eg, generate it for each hashtable dynamicly), the adversarial can not easily attack it.

The wyhash64 function is a utility function for myself, independent of wyhash function release. In programing, sometimes I need to quickly mix one or two uint64_t. I do not expect wyhash64 to be secure but to be fast. For example, I use wyhash64(time(NULL),0) to seed a PRNG, or use wyhash64(i,j) for act as a random mapping of loop variable i and j.
