### ISSUE TITLE
Unexpected behavior of the new _wymum with WYHASH32

### ISSUE THREAD

**Issue by ivte-ms** [wangyi-fudan/wyhash#39]
Regarding this update: https://github.com/wangyi-fudan/wyhash/commit/fd9229f2fdeed17ed62c77de054ce3035d85475b

Consider this snippet (includes and common functions are omitted):
```
uint64_t _wymum64(uint64_t A, uint64_t B) {
  A = _umul128(A, B, &B);
  return A ^ B;
}

uint64_t _wymum32_old(uint64_t A, uint64_t B) {
  uint64_t hh = (A >> 32) * (B >> 32), hl = (A >> 32) * (unsigned)B,
           lh = (unsigned)A * (B >> 32),
           ll = (uint64_t)(unsigned)A * (unsigned)B;
  return _wyrotr(hl, 32) ^ _wyrotr(lh, 32) ^ hh ^ ll;
}

uint64_t _wymum32_new(uint64_t A, uint64_t B) {
  uint64_t c = A ^ B;
  return ((c >> 32) * (unsigned)c) ^
         _wyrotr(((A >> 32) * (unsigned)A) ^ ((B >> 32) * (unsigned)B), 32);
}

int main() {
  for (uint64_t a = 100; a < 105; ++a) {
    for (uint64_t b = 100; b < 105; ++b) {
      std::cout << "A: " << a << " B: " << b
          << " _wymum64: " << _wymum64(a, b)
          << " _wymum32_old: " << _wymum32_old(a, b)
          << " _wymum32_new: " << _wymum32_new(a, b) << '\n';
    }
  }
}
```
The output for me (VS2019) is:

> A: 100 B: 100 _wymum64: 10000 _wymum32_old: 10000 _wymum32_new: 0
> A: 100 B: 101 _wymum64: 10100 _wymum32_old: 10100 _wymum32_new: 0
> A: 100 B: 102 _wymum64: 10200 _wymum32_old: 10200 _wymum32_new: 0
> A: 100 B: 103 _wymum64: 10300 _wymum32_old: 10300 _wymum32_new: 0
> A: 100 B: 104 _wymum64: 10400 _wymum32_old: 10400 _wymum32_new: 0
> A: 101 B: 100 _wymum64: 10100 _wymum32_old: 10100 _wymum32_new: 0
> A: 101 B: 101 _wymum64: 10201 _wymum32_old: 10201 _wymum32_new: 0
> A: 101 B: 102 _wymum64: 10302 _wymum32_old: 10302 _wymum32_new: 0
> A: 101 B: 103 _wymum64: 10403 _wymum32_old: 10403 _wymum32_new: 0
> A: 101 B: 104 _wymum64: 10504 _wymum32_old: 10504 _wymum32_new: 0
> A: 102 B: 100 _wymum64: 10200 _wymum32_old: 10200 _wymum32_new: 0
> A: 102 B: 101 _wymum64: 10302 _wymum32_old: 10302 _wymum32_new: 0
> A: 102 B: 102 _wymum64: 10404 _wymum32_old: 10404 _wymum32_new: 0
> A: 102 B: 103 _wymum64: 10506 _wymum32_old: 10506 _wymum32_new: 0
> A: 102 B: 104 _wymum64: 10608 _wymum32_old: 10608 _wymum32_new: 0
> A: 103 B: 100 _wymum64: 10300 _wymum32_old: 10300 _wymum32_new: 0
> A: 103 B: 101 _wymum64: 10403 _wymum32_old: 10403 _wymum32_new: 0
> A: 103 B: 102 _wymum64: 10506 _wymum32_old: 10506 _wymum32_new: 0
> A: 103 B: 103 _wymum64: 10609 _wymum32_old: 10609 _wymum32_new: 0
> A: 103 B: 104 _wymum64: 10712 _wymum32_old: 10712 _wymum32_new: 0
> A: 104 B: 100 _wymum64: 10400 _wymum32_old: 10400 _wymum32_new: 0
> A: 104 B: 101 _wymum64: 10504 _wymum32_old: 10504 _wymum32_new: 0
> A: 104 B: 102 _wymum64: 10608 _wymum32_old: 10608 _wymum32_new: 0
> A: 104 B: 103 _wymum64: 10712 _wymum32_old: 10712 _wymum32_new: 0
> A: 104 B: 104 _wymum64: 10816 _wymum32_old: 10816 _wymum32_new: 0

You can adjust `a` and `b` to pretty high values, the result of the new _wymym will stay 0 (I picked the range between 100 and 105 just as an example).
I don't know if this is a problem for the overall result or not, but it looks suspicious. Is this the expected behavior?

**Comment by wangyi-fudan** [comment]
roll back as it fails PRNG test.
