### ISSUE TITLE
any way to avoid unaligned reads?

### ISSUE THREAD

**Issue by haberman** [wangyi-fudan/wyhash#4]
I think wyhash looks really promising and am considering using it in my project. Looking at the code, it seems like it will perform unaligned reads from memory if the input isn't aligned. This is undefined behavior, and while it works fine on architectures like x86, some architectures will generate hardware exceptions for unaligned reads. More info here: https://stackoverflow.com/questions/32062894/take-advantage-of-arm-unaligned-memory-access-while-writing-clean-c-code

Perhaps you could add some (optional) code to handle this? Maybe something like this?

```c++
unsigned long long wyhash_nounaligned(const void* key, unsigned long long len, unsigned long long seed) {
  const	unsigned char *ptr=(const unsigned char*)key;
  int remainder = (uintptr_t)ptr & 7;
  if (len < 32 && remainder) {
    union {
      long long align;  // Ensure 8-byte alignment of buffer.
      char buf[8];
    } tmp;
    int patch = 8 - remainder;
    memcpy(&tmp.buf, ptr, patch);
    seed = wyhash(tmp.buf, patch, seed);
    ptr += patch;
    len -= patch;
  }
  return wyhash(ptr, len, seed);
}
```

**Comment by wangyi-fudan** [comment]
solved. Many thanks!
