### ISSUE TITLE
Please provide test vectors.

### ISSUE THREAD

**Issue by leo-yuriev** [wangyi-fudan/wyhash#43]
For instance like this ([#1](https://github.com/leo-yuriev/t1ha/blob/b8eefd2ce0ca7de080e9972645d3433aa9fe5d20/tests/test.c#L59-L117), [#2](https://github.com/leo-yuriev/t1ha/blob/b8eefd2ce0ca7de080e9972645d3433aa9fe5d20/tests/wyhash/wyhash_thunk.c#L31-L51)).

**Comment by wangyi-fudan** [comment]
done.
