### ISSUE TITLE
wyhash V5 draft is out

### ISSUE THREAD

**Issue by wangyi-fudan** [wangyi-fudan/wyhash#47]
Dear friends:
  wyhash V5 draft is out. It make _wyp as variable secrets. By assuming _wyp as secrets, we reduced one xor operation and make the bulk speed crazy.
  Tomorrow, I will write a help-function to generate secrets from a random uint64_t.
  Exciting!

**Comment by wangyi-fudan** [comment]
The draft becomes a version now. As you known, I update it too quickly because I stay at home due to the flu. Test it and enjoy it but no hurry to update :-)

**Comment by ktprime** [comment]
__builtin_popcountll can not used on ms vc++(_mm_popcnt_u64)

**Comment by wangyi-fudan** [comment]
done.
In order to be fast, I also provide WYHASH_PART define, which means no avalanche finalization is performed. It breaks many quallity rules, however, it offer uncompetable performance for hash table.
hash    short   hashmap bulk16M
wyhash_part  281.818 53.466  23.536
wyhash  258.874 47.490  23.873

**Comment by ktprime** [comment]
add support  clang compiler with marco __clang__

**Comment by wangyi-fudan** [comment]
I am not familar with clang, can you help me by a pull request?

**Comment by ktprime** [comment]
your can download form https://github.com/llvm/llvm-project/releases/tag/llvmorg-9.0.1,
use is same as gcc on no-win os. And it can be easy integrated in vs 2017/2019.

**Comment by ktprime** [comment]
I have change some of your code https://github.com/ktprime/emhash/blob/master/thirdparty/wyhash.h

**Comment by gzm55** [comment]
try https://travis-ci.org/ to trigger test matrix for all supported compilers after each commit

**Comment by gzm55** [comment]
in `_wyhash` function, the bulk processing part could be implemented via SSE/AVX instructions.

**Comment by wangyi-fudan** [comment]
really? I know that AVX has 32 X 32 => 64 function, but what I need is 64 X 64 =>128 function. would you give me more hints （instruction name)? thanks!

**Comment by wangyi-fudan** [comment]
PMULUDQ ?

**Comment by gzm55** [comment]
yes, 64bit MUL can only get low 64bit result now.

But vectorizing 32-bit version MUM could still speed up for long keys.

PS, v5 is a little slow for shot keys, although reducing one xor operation, but we could have to use cycles for loading memory from `secret[6]` not `const _wyp*`.

**Comment by lemire** [comment]
This may be relevant:

[Faster 64-bit universal hashing using carry-less multiplications](https://arxiv.org/abs/1503.03465), Journal of Cryptographic Engineering 6(3), 2016

[Source code](https://github.com/lemire/clhash)

**Comment by wangyi-fudan** [comment]
> But vectorizing 32-bit version MUM could still speed up for long keys.
the magic is 32 X 32 will fail tests, while 64 X 64 passes tests.

> PS, v5 is a little slow for shot keys, although reducing one xor operation, but we could have to use cycles for loading memory from `secret[6]` not `const _wyp*`.
you can make_secret offline, write it to a include file as constant.

**Comment by cocowalla** [comment]
I doubt it helps here, but my [C# port](https://github.com/cocowalla/wyhash-dotnet/blob/master/src/WyHash/WyCore.cs#L51) uses [BMI2's MULX](https://www.felixcloutier.com/x86/mulx) operation, which gives both the high and parts in a single operation, providing a nice speed up.

But I would presume the C compiler would automatically use this, or an equivelant.

**Comment by lemire** [comment]
On x64, you can always get the low and high 64-bit components in one instruction. The mulx is there mostly to help with dependencies.

**Comment by cocowalla** [comment]
> On x64, you can always get the low and high 64-bit components in one instruction. The mulx is there mostly to help with dependencies.

Not in .NET you don't :confounded:
