### ISSUE TITLE
madhash

### ISSUE THREAD

**Issue by wangyi-fudan** [wangyi-fudan/wyhash#48]
I would like to introduce the madhash. It samples up to 32 byte of the data to produce a hash.
It breaks every rules, however, it is valid to short string hashing up to 32 byte. for longer strings, it is a bad guy but works. The bulk speed is insane...

Benchmarking    /usr/share/dict/words
HashFunction    Words   Hashmap Bulk64K Bulk16M
madhash         303.92  50.70   11295.11        2863311.53
std::hash       96.09   36.57   7.34    7.36
wyhash          265.71  45.59   26.35   21.78
xxHash64        110.84  35.85   14.71   14.58
XXH3_scalar     183.82  42.64   13.09   13.05
t1ha2_atonce    127.93  36.26   16.60   16.32

**Comment by wangyi-fudan** [comment]
I rename madhash to the FastestHash, which only consider head and tail 8 bytes.  I think it is a "canonical" hash function as it has no paramters. Though it is bad, it simply works for hash tables.

Benchmarking    /usr/share/dict/words
HashFunction    Words   Hashmap Bulk64K Bulk16M
FastestHash     312.69  52.17   12341.86        3435973.84
std::hash       96.09   36.85   7.37    7.36
wyhash          274.03  47.97   26.84   22.96
xxHash64        109.20  36.98   14.71   14.58
XXH3_scalar     181.58  44.01   13.09   13.10
t1ha2_atonce    128.20  37.58   17.09   16.76

**Comment by ktprime** [comment]
it's a great for hash users.
