### ISSUE TITLE
Provide suggested secrets or secret seed for v5

### ISSUE THREAD

**Issue by gzm55** [wangyi-fudan/wyhash#53]
From v5, we have to generate secrets before hashing. Even though we have `make_secret()` helper function, getting qualified secrets still requires many knowledge about this project and other benchmark/testing frameworks, and  spends hours to run many test cases. The testing results vary on different secret. For current v5 dev version (`master@36aec06`), about 20% of 1-byte seeds for `make_secret` fails rurban/smhasher. After many testing, it's a little lucky to find `make_secret(13, secret)` give out a group secrets passing rurban/smhasher, demerphq/smhasher and `LongNeighborsTest` from hmakholm/smhasher. When the hash algorithm updates, it have to search qualified secrets from zero.

So, when the codes become stable, it could be better to lock **a default group of secrets** that can pass all/most test cases.

**Comment by dumblob** [comment]
>So, when the codes become stable, it could be better to lock **a default group of secrets** that can pass all/most test cases.

My words!

**Comment by wangyi-fudan** [comment]
I see. in fact _wyp in previous version is very good. Let me do it tomorrow.

**Comment by wangyi-fudan** [comment]
done
