### ISSUE TITLE
make_secret() seems not guaranteed to return

### ISSUE THREAD

**Issue by dumblob** [wangyi-fudan/wyhash#54]
Is the following loop guaranteed to end or is there a chance of infinite looping (depending on the given seed)?

```c
...
  }while(!ok);
```
I'd say there should be detection of some fixed number of iterations and if that won't be enough, then just return some error. Or better, make the function always succeed :wink: (without sacrificing entropy from the seed).

**Comment by wangyi-fudan** [comment]
It is guaranteed... because wyrand visit all 2^64 status. if some seed works, one day you will visit these working seed. ;-)
However, 2^64 is a bit number, take it easy, usually it works quickly. 
We just need to find a number that popount(Ni^Nj)==32 which is easy.

**Comment by dumblob** [comment]
Now I looked at the code again (didn't do any analysis though) and somehow I still have a subtle feeling, that it would be possible to construct the seed in a way which would make `secret[i]^secret[j]` always yield popcount of 32 (it depends on popcount of all pair-wise combinations of numbers in the `c[]` array and on the 0-63 previous iterations of the `j` inner for loop as well as on the 0-4 previous iterations of the outer/main for loop).

How did you generate the numbers in `c[]`? If it's guaranteed that for each constellation of these numbers there exists at least one combination yielding different popcount than 32, then all is good :wink:.

**Comment by wangyi-fudan** [comment]
c are bytes with popcount==4

**Comment by dumblob** [comment]
Oh man, my bad - I misread `ok=0` as `ok=1`. Thanks for the explanation!
