### ISSUE TITLE
v5 default key fails MomentChi2 and Sparse

### ISSUE THREAD

**Issue by gzm55** [wangyi-fudan/wyhash#57]
On my local testing:

> wyhash secret[0]: 0xa0761d6478bd642f
> wyhash secret[1]: 0xe7037ed1a0b428db
> wyhash secret[2]: 0x8ebc6af09c88c6e3
> wyhash secret[3]: 0x589965cc75374cc3
> wyhash secret[4]: 0x1d8e4e27c47d124f
> 
> [[[ Keyset 'Sparse' Tests ]]]
> Worst bias is the 13-bit window at bit 11 - 1.045% !!!!!
>
> [[[ MomentChi2 Tests ]]]
> 
> Running 1st unseeded MomentChi2 for the low 32bits/step 3 ... 38917465.185213 - 410425.007092
> Running 2nd   seeded MomentChi2 for the low 32bits/step 3 ... 38919451.497948 - 410461.736885
> KeySeedMomentChi2:      4.80631 FAIL!!!!

**Comment by wangyi-fudan** [comment]
not bad fail.
fixed.
my bad. thanks!
