### ISSUE TITLE
wyhash_v6 is coming

### ISSUE THREAD

**Issue by wangyi-fudan** [wangyi-fudan/wyhash#58]
Dear All:
  Based on recent experiments, wyhash_v6 with avx2 support is coming. some preliminary 
benchmark here, let's meow:

Benchmarking    /usr/share/dict/words
HashFunction    Words   Hashmap Bulk64K Bulk16M
std::hash       96.28   34.17   7.34    7.36
MeowHash        73.90   25.59   37.18   26.88
wyhash_v6_avx2  253.69  44.53   40.26   25.74
xxHash64        105.03  35.13   14.70   14.62
XXH3_avx2       185.96  40.64   27.89   23.21
t1ha2_atonce    127.92  34.68   17.10   16.81

**Comment by wangyi-fudan** [comment]
done

**Comment by wangyi-fudan** [comment]
And I want to sincerely say some sorry to @Cyan4973. I am just a childish person at age of 40 ...

**Comment by gzm55** [comment]
it's time to copy a separate `wyhash_v5.h` ?

**Comment by wangyi-fudan** [comment]
done. and let's wait a few days to update the stream version.

**Comment by gzm55** [comment]
many warnings

> from 'long unsigned int' to 'long long int' [-Wnarrowing]

should use explicit conversions instead, e.g. `(int64_t)seed`, `(int64_t)secret[x]`

**Comment by wangyi-fudan** [comment]
done.

**Comment by ktprime** [comment]
_wyhash (key=<optimized out>, len=<optimized out>, seed=8383780068391013234, secret=secret@entry=0x44c860 <_wyp>) at wyhash.h:102
102       __m128i d[8]={_mm_loadu_si128((__m128i*)p),_mm_loadu_si128((__m128i*)(p+16)),_mm_loadu_si128((__m128i*)(p+32)),_mm_loadu_si128((__m128i*)(p+48)),
(gdb) bt
#0  _wyhash (key=<optimized out>, len=<optimized out>, seed=8383780068391013234, secret=secret@entry=0x44c860 <_wyp>) at wyhash.h:102
#1  0x000000000042ad03 in wyhash (seed=<optimized out>, len=<optimized out>, key=<optimized out>) at wyhash.h:123
#2  emhash6::HashMap<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::hash_bucket<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, 0u> (key=<error: Cannot access memory at address 0xffffffffffffffff>, this=0x7fffffffe270) at hash_table56.hpp:1632
#3  emhash6::HashMap<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::rehash (this=this@entry=0x7fffffffe270, 
    required_buckets=required_buckets@entry=6) at hash_table56.hpp:1113
#4  0x00000000004053d5 in emhash6::HashMap<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::reserve (num_elems=4, this=0x7fffffffe270)
    at hash_table56.hpp:1060
#5  emhash6::HashMap<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::init (load_factor=0.949999988, bucket=4, this=0x7fffffffe270)
    at hash_table56.hpp:345
#6  emhash6::HashMap<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::HashMap (load_factor=0.949999988, bucket=4, this=0x7fffffffe270)
    at hash_table56.hpp:350
#7  main (argc=1, argv=0x7fffffffe408) at mbench.cpp:970

**Comment by wangyi-fudan** [comment]
what does these information mean? could you explain it to us :-)

**Comment by ktprime** [comment]
wyhash v6 in used int my hash map.  I change the code and use the follow:

static inline uint64_t wyhash(const void* key, uint64_t len, uint64_t seed){  uint64_t h=_wyhash(key,len,seed,_wyp)^len; return _wymum(h,h^_wyp[9]);}
