### ISSUE TITLE
License not defined

### ISSUE THREAD

**Issue by oertl** [wangyi-fudan/wyhash#6]
Are there any plans to define a license? I am asking, because I have seen that very first versions have been published under Apache 2.0.

**Comment by wangyi-fudan** [comment]
I removed the lisence and want to make it completely free. I am not sure whether this is the best way.

**Comment by wangyi-fudan** [comment]
I updated the readme.md to declare it is completely free.

**Comment by oertl** [comment]
It is great to make it free! Nevertheless, I would recommend to define a license to make this even more clear. There are quite permissive licenses like "The Unlicense" (see https://choosealicense.com/licenses/unlicense/) which could fit here.

**Comment by wangyi-fudan** [comment]
done! :-)
