### ISSUE TITLE
Use Git Tags for Versions

### ISSUE THREAD

**Issue by felixguendling** [wangyi-fudan/wyhash#61]
I have some trouble finding the latest stable version of the hash. Furthermore, I'm confused since there are several variants: FastestHash and wyhash. Is there a guide on when to use which? Or is it that one of them is always the best? Then why would you keep the other one?

For wyhash the repository contains several versions at the same time. Which one should I use? If only the latest is relevant: why not tag the older versions (using Git tags) and remove it from the master/HEAD? This way it's clear which version is the preferred one but older versions are still easily accessible.

The current version contains large chunks of commented out code. Is this code still relevant or can it be removed entirely? If it's just for historical reasons: why not archive it using Git? It will still be available through the Git history of the repository.

**Comment by wangyi-fudan** [comment]
thanks for your commnet. I will try to improve it later.
you should use wyhash.h 
wyhash_v? is old version, but I want to keep them.
FastestHash is an insecure hash. If you just want hashmap speed, you can try it. For general purpose,  use wyhash
