### ISSUE TITLE
wyhash_beta version is ready

### ISSUE THREAD

**Issue by wangyi-fudan** [wangyi-fudan/wyhash#64]
Yann Collet discovered that early wyhash has 62 bit uniqueness strength. https://github.com/Cyan4973/xxHash/wiki/Collision-ratio-comparison
The wyhash_beta version solved the problem.

And now wyhash is optimized for a new benchmark: 0-31 random byte test. It generate 0-31 unpredictable random length according to hash result, thus do not require a PRNG. I PRed smhasher.

**Comment by easyaspi314** [comment]
> And now wyhash is optimized for a new benchmark

How come I feel that this is the other way around?
