### ISSUE TITLE
Make things neater and more professional

### ISSUE THREAD

**Issue by easyaspi314** [wangyi-fudan/wyhash#65]
There are many things that are generally messy and unprofessional about this repo.

First of all, as mentioned before in #34 and #61, the way you are using git is rather poor:
  - You are doing everything in the GitHub web editor, this is literally the most inefficient way of doing this.
  - Commit messages are still left out. Even if it seems redundant, it helps a lot. Even something as simple as `fix typo` is better than `Update README.md`, `Add files via upload`, etc. That way you can get an idea of what change each commit made without having to look at the diff itself.
  - Make small changes which can easily be undone.

If I am not mistaken, it seems you don't know how to use `git`. Don't fear `git`: Out of the hundreds of options, you will rarely ever use more than 20, and you can get away with only partially knowing 10. I can help you if you can't find a resource online that works for you.

Second of all, your code is very messy.

Code should be treated like a work of art, or at the very least, kept relatively organized.

If you want others to be comfortable with your code enough to use/contribute to it, they have to be able to understand it. This means making things easy to read, at least trying to stick to a code style, and documenting everything.

**Nobody cares if the source code is tiny**, including the compiler. The only place where that matters is JavaScript, but minified JavaScript is usually "compiled" from normal source code. 

Obviously, nobody wants a 2 MB source file, but nobody cares about a few extra kilobytes, especially if it improves readability. 

Would you rather read this:
```c
static inline uint64_t FastestHash(const void *key, size_t len, uint64_t seed) {
	const uint8_t *p = (const uint8_t *)key;
	return _likely_(len >= 4) ? (_wyr4(p) + _wyr4(p + len - 4)) * (_wyr4(p + (len >> 1) - 2) ^ seed) : (_likely_(len) ? _wyr3(p, len) * (*_wyp ^ seed) : seed);
}
```
or this?
```c
// A quick and dirty hash for very short keys.
// It is not secure by any means; it aims only to be fast.
// This only reads a sample of up to 12 bytes, ignoring
// the rest. This makes it unsuitable for long hashes.
static inline uint64_t FastestHash(const void *key, size_t len, uint64_t seed)
{
    const uint8_t *input = (const uint8_t *)key;
    if (_likely_(len >= 4)) {
        // Read the first, middle, and last 4 bytes.
        uint64_t first_4 = _wyr4(input);
        uint64_t last_4  = _wyr4(input + len - 4);
        uint64_t mid_4   = _wyr4(input + (len >> 1) - 2);
        // Mix and multiply.
        return (first_4 + last_4) * (mid_4 ^ seed);
    } else if (_likely_(len != 0)) {
        // Mix with _wyp and multiply.
        return _wyr3(input, len) * (_wyp[0] ^ seed);
    }
    // Return the seed on a zero-length hash.
    return seed;
}
```
It is significantly more readable, easier to contribute to and analyze, and GCC and Clang generate exact same code. (Compilers break things up into single steps and reorder any way they want, so combining into ternaries and other nonsense is pointless)

Also, please don't put commented out blocks of code in the repo — it is fine locally when testing, but nobody wants to look at [this](https://github.com/wangyi-fudan/wyhash/blob/9968d74a29a90abad47ce4bc64af1b3f6425b5ea/wyhash_alpha.h#L119) 

Lastly, everything should be ready to compile and run from a fresh clone. This is unacceptable:

```
$ git clone https://github.com/wangyi-fudan/wyhash
$ cd wyhash
$ make
make: *** No rule to make target 'wyhash/wyhash.h', needed by 'benchhash'.  Stop.
```

Also, what is up with `supplemental_material.zip`? `git` repos are compressed already, and the extra disk space is insignificant.

**I'd be happy to help with this** — I love making things neat and writing/proofreading documentation — but I really don't want to [put time into cleaning things up](https://github.com/wangyi-fudan/wyhash/commit/fcbda4576bd98bfb3e598957434ed0afced6c99c) if you are going to just [throw it all away](https://github.com/wangyi-fudan/wyhash/commit/6af92157f89045b85f65161173150b05efb3c582). I'd be seriously disappointed (and slightly offended), and I feel the other people who tried to clean things up feel the same way.

**Comment by wangyi-fudan** [comment]
Thanks very much.
The problem of myself is that my "brain memory" is very limited. I feel like hell when reading more than 100 lines of code. That's why I have to keep every thing minimal. Sorry, maybe I am a bit strange at this points.

**Comment by easyaspi314** [comment]
> my "brain memory" is very limited. I feel like hell when reading more than 100 lines of code.

That is 100% normal.

I think the problem is that you have trouble splitting it up internally.

Yann and I made sure everything was split up when making XXH3; it would be completely overwhelming if it wasn't.

For example, here is 70 lines of XXH3:
![XXH3 unsplit](https://user-images.githubusercontent.com/6258309/76475035-05381700-63d4-11ea-95e7-c8979c6d7f9c.png)

If you process it as 70 lines, yeah, you'll go insane. And that is just the code for lengths 0-16!

Meanwhile, if you look at it on a function level, it is much less overwhelming:

![XXH3 split](https://user-images.githubusercontent.com/6258309/76475083-31ec2e80-63d4-11ea-9f96-b223f56802aa.png)

**Comment by easyaspi314** [comment]
My comments served the same purpose in my version of FastestHash:
![fastest hash split](https://user-images.githubusercontent.com/6258309/76475579-b8554000-63d5-11ea-9728-0a8bf3540505.png)

**Comment by wangyi-fudan** [comment]
We can have a beautifual version for the reader, and an ugly/compressed version for me :-)

**Comment by gzm55** [comment]
@wangyi-fudan

**Comment by gzm55** [comment]
IMO, sometimes for a small repo,  committing a piece of codes to `github.com`, is very like publishing/updating a paper to `arxiv.org`. We need those words, paragraphs, sections, formulas and diagrams to explain some research and results to others. It is hard to read or understand a paper without abstracts, proper sections, or typesetting the formulas in word instead of LaTeX, although this paper would still give out an outstanding achievement in its domain. In terms of coding, the way of organizing the files/functions/classes not only benefits the runtime performance, but also make other co-workers (including the author in the future) to better understand and spread the project.

> keep every thing minimal

Information from fewer `lines` are not have to be less than that from more lines.  Keeping minimal (K.I.S.S) is a good principle for reducing complexity of designing. But merging things into one line is just like putting all things into one big box, while a better way is classifying and putting into some labeled small boxes. When reading each version of wyhash.h, i have to read through many times for getting the point of a very complex line. When reading the xxh, understanding the main part consumes about 1~2 hour, and most 'screen's are clear for one through, the hard parts are also well documented.

So if you wanna a minimal thing, the correct part is for simplifying internal logic. For code lines, try to fit a function into one 'screen', (40--60 lines, 80--100 columns). If some long lines are really complex, some well named one-time variables can easily split them into 2~3 short lines without any run time cost.

**Comment by wangyi-fudan** [comment]
thanks! I will follow your ideas!

**Comment by easyaspi314** [comment]
I am glad to see you followed my suggestions on the commit messages and used my code without even mentioning me… :unamused:

**Comment by easyaspi314** [comment]
Here is a summary:

 - Please learn how to use `git`, it is easier than using GitHub's web editor.
 - Always use commit messages, even if you think you don't need them.
 - Format and comment your code. 
 - Set up the project so you can run `make` without changing anything.

If it makes it easier to understand, I translated it to Chinese:

如果它更易于理解，我将其翻译为中文：

总结如下：
  - 请学习如何使用`git`，它比使用GitHub的网络编辑器更容易。
  - 始终使用提交消息，即使您认为不需要它们也是如此。
  - 格式化并注释您的代码。
  - 设置项目，以便您无需更改即可运行`make`。
