### ISSUE TITLE
gamma version is only compiled on gcc

### ISSUE THREAD

**Issue by gzm55** [wangyi-fudan/wyhash#66]
__uint128_t is a gcc extension, which do not works on msvc and clang

**Comment by wangyi-fudan** [comment]
yes, I am working on assembly...

**Comment by gzm55** [comment]
another problem:

```c
 seed=_wymix128(_wymix128((_wyread128(p)<<((16-len)<<3))^seed^_wyp)^len0); 
```

the last read 128 will read the bytes beyond the length, is not safe.

**Comment by wangyi-fudan** [comment]
yes, intended. trade with great speed...
And I find that when compile to assmbly, the speed is even faster... crazy.

**Comment by gzm55** [comment]
ok, still better to select optimized and safe codes by compile time macros.

**Comment by wangyi-fudan** [comment]
> __uint128_t is a gcc extension, which do not works on msvc and clang
 now, only use uint64_t
