### ISSUE TITLE
Hash function versus PRNG function

### ISSUE THREAD

**Issue by dumblob** [wangyi-fudan/wyhash#68]
A quote from http://www.reedbeta.com/blog/quick-and-easy-gpu-random-numbers-in-d3d11/ :

>Incidentally, I was confused for a long time about the distinction between PRNGs and hash functions—they seem to do the same thing, i.e. create an “unpredictable” but deterministic output by jumbling up input bits. It wasn’t until I started playing around with GPU PRNGs that I realized the difference: PRNGs are designed for going deep, and hashes for going wide.

@wangyi-fudan could you maybe shed some light how wyhash performs as PRNG - i.e. when going "deep" instead of wide?

**Comment by wangyi-fudan** [comment]
some random commnets:
1: wyhash can be used as PRNG by hashing time or a increasing number
2: wyhash64(i,j) can be used as a determinstic PRNG.
for(i=0;i<10;i++) 
  for(j=0;j<10;j++)
    wyhash64(i,j)
this is useful in my neural network code.
3: a specially developed wyrand is for PRNG only. it is  the fastest PRNG with good quality.
4: wy2u01, wy2gau convert random 64 bit for uniform and gaussian distribution. they can be combined with above functions:
wy2u01(wyhash64(i,j))
see all function in wyhash.h can work togather :-)

**Comment by dumblob** [comment]
Any PRNG tests performed? I'm just curious as I don't have currently any use case for such PRNG, so no need to hurry with your answer :wink:.

**Comment by wangyi-fudan** [comment]
wyrand have been extensivly tested: passing both practrand and bigcrush.

**Comment by dumblob** [comment]
Sorry for asking so many questions, but while at it, have you also tested with practrand and bigcrush the code you've suggested above?
```
for(i=0;i<10;i++)
for(j=0;j<10;j++)
wyhash64(i,j)
```

**Comment by wangyi-fudan** [comment]
> Sorry for asking so many questions, but while at it, have you also tested with practrand and bigcrush the code you've suggested above?
> 
> ```
> for(i=0;i<10;i++)
> for(j=0;j<10;j++)
> wyhash64(i,j)
> ```

wyhash64 has not been test, because I don't know how to load it the PRNG test.
However, as it is very similar to wyhash (two round of MUM), I belive it works.

**Comment by wangyi-fudan** [comment]
I will test wyhash64 tonight. It is really an useful component.

**Comment by wangyi-fudan** [comment]
roll back to early version of wyhash64, it now passed practrand (more than 6 hour buring, no fail).
