### ISSUE TITLE
Usage Example

### ISSUE THREAD

**Issue by singularian** [wangyi-fudan/wyhash#83]
Can you add a usage example for wyhash.h and the wyhash function?

How big can we make the wy hash secret?

wyhash(bytes, size, wyseed, (const uint64_t*) wysecret64);

**Comment by wangyi-fudan** [comment]
In fact I use
wyhash(pointer,length,seed,_wyp);
where _wyp is defined in the wyhash.h file.
If you think safe is more important, then you generate your own secret.

**Comment by singularian** [comment]
So it's length 5 for the _wyp secret?
That's what I was reading. Can you make it longer?

const uint64_t _wyp[5] = {0xa0761d6478bd642full, 0xe7037ed1a0b428dbull, 0x8ebc6af09c88c6e3ull, 0x589965cc75374cc3ull, 0x1d8e4e27c47d124full};
