### ISSUE TITLE
absl hash use wyhash

### ISSUE THREAD

**Issue by ktprime** [wangyi-fudan/wyhash#86]
the fastest hashmap absl now use wyhash(replace cityhash) as default hash function

https://github.com/abseil/abseil-cpp/blob/master/absl/hash/internal/wyhash.cc

**Comment by data-man** [comment]
> the fastest hashmap absl 

Really? :smile:

**Comment by ktprime** [comment]
from my full bench on 3 os(linux, win, mac), 3 compilers(gcc, clang, msvc), 3 cpu(arm64, x86, x86_32)) , 10 different k.v , hash fuction and load_factor, 10 different cases combination. absl is average 10% fast than other hashmaps.

**Comment by wangyi-fudan** [comment]
great news! add it in readme
The wyhash used is an old version. maybe absl+wyhash_final_2 will be faster :-D
