### ISSUE TITLE
Inconsistent size and use of `secret`

### ISSUE THREAD

**Issue by wclodius2** [wangyi-fudan/wyhash#90]
In the current version of `wyhash.h` there is a void function, `make_secret` that makes an "array" called `secret` with five elements, and there is a `const` array, `wyp`, with five elements that is described as the default version of `secret`. However, in the code, only four elements of secret are used: `secret[0]`, `secret[1]`, `secret[2]`, and `secret[3]`. The code would take up a little less space and be otherwise unchanged if `secret` and `wyp` were four element arrays.

**Comment by wangyi-fudan** [comment]
OK, thanks! updated.
