### ISSUE TITLE
Apple Silicon likes wyhash

### ISSUE THREAD

**Issue by lemire** [wangyi-fudan/wyhash#94]
Apple’s M1 processor and the full 128-bit integer product
https://lemire.me/blog/2021/03/17/apples-m1-processor-and-the-full-128-bit-integer-product/

(I am just pinging you. It is not an actual issue.)

**Comment by wangyi-fudan** [comment]
Dear Lemire:
Nice to hear from you!
The PRNG you called wyhash is an old developing version that requires two MUM.
Now I suggest using wyrand PRNG which requires one MUM thus faster.

**Comment by lemire** [comment]
@wangyi-fudan The important idea would still hold, I expect.

(I am closing this since you have seen the comment.)
