### ISSUE TITLE
signed 128bit multiplication

### ISSUE THREAD

**Issue by gzm55** [wangyi-fudan/wyhash#97]
wyhash currently use unsigned 64x64->128 multiplication, which will be compiled to a single `MUL` instruction on x64 arch. 
It should not slow down the performance when using the signed multiplication instead, which should be compiled to an `IMUL` instruction.

When porting to java, since all multiplications are signed, even jdk 10+ has optimized `Long. multiplyHigh()`, it still affect about 20% performance for short keys.

Using unsigned mulplication on jdk11:

```bash
Benchmark                   (algo)  (length)  Mode  Cnt    Score     Error  Units
HashBench.withArray  wyhash.final3        32  avgt    5   13.481 ±   1.895  ns/op
HashBench.withArray  wyhash.final3       512  avgt    5   90.096 ±  13.429  ns/op
HashBench.withArray  wyhash.final3      2048  avgt    5  339.363 ±  56.848  ns/op
```

Using signed mulplication on jdk11:
```bash
Benchmark                   (algo)  (length)  Mode  Cnt    Score     Error  Units
HashBench.withArray  wyhash.final3        32  avgt    5   11.137 ±   1.974  ns/op
HashBench.withArray  wyhash.final3       512  avgt    5   61.593 ±  14.877  ns/op
HashBench.withArray  wyhash.final3      2048  avgt    5  318.038 ± 334.272  ns/op
```

**Comment by wangyi-fudan** [comment]
Based on this observation, do you mean we should keep unsigned version? right?

**Comment by gzm55** [comment]
we should be better to switch to **signed** full 64b multiplication.

**Comment by wangyi-fudan** [comment]
interesting. See if we can do that.

**Comment by gzm55** [comment]
[here](https://github.com/OpenHFT/Zero-Allocation-Hashing/blob/master/src/main/java/net/openhft/hashing/Maths.java#L44) is the java code to mimic an unsigned mul with a signed one.

**Comment by wangyi-fudan** [comment]
hi, I tried it. 
just change the mum function to int64_t. 
I found that the speed is down. 
So based on this preliminary observation plus the personal preference of uint64_t, I think we should not switch to int64_t now.

**Comment by gzm55** [comment]
fail enough~ the reason would be interesting~

**Comment by lemire** [comment]
> I found that the speed is down.

I find this surprising. One potential benefit of the unsigned multiplication on x64 systems is mulx which, as far as I can tell, is for unsigned multiplications only... but is this what is happening here ? I doubt it because mulx requires a recent processor.

I am not arguing that you should change your code... I am just surprised that there is a significant performance implication in C.

Otherwise, I think Java should just support unsigned multiplications.

**Comment by gzm55** [comment]
> Otherwise, I think Java should just support unsigned multiplications.

that could be a whole century. 

Maybe the sign extension for `IMUL` slow down the instruction.

**Comment by lemire** [comment]
> that could be a whole century.

I am more optimistic. Java is evolving quickly.

> Maybe the sign extension for IMUL slow down the instruction

We do have the latencies and throughput of these instructions and MUL and IMUL have the same performance, down to the cycle. These things are documented. If signed multiplications were slower, we would know.
