### ISSUE TITLE
include test code in the repository

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [wangyi-fudan/wyhash#98]
Hello 王一 WangYi.

1. I implemented `python/cython` wrapper for the "test vectors for portability test":

https://github.com/wangyi-fudan/wyhash/blob/b5b0aa2437126cc7a5abffdd9f5727dbd7a0ebc6/wyhash.h#L194
```c
wyhash("",0,_wyp)=42bc986dc5eec4d3
wyhash("a",1,_wyp)=84508dc903c31551
wyhash("abc",2,_wyp)=bc54887cfc9ecb1
wyhash("message digest",3,_wyp)=adc146444841c430
wyhash("abcdefghijklmnopqrstuvwxyz",4,_wyp)=9a64e42e897195b9
wyhash("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789",5,_wyp)=9199383239c32554
wyhash("12345678901234567890123456789012345678901234567890123456789012345678901234567890",6,_wyp)=7c1ccf6bba30f5a5
``` 

2. surprisingly, the test works fine (value matches) for 6 out of 7 entries, and fails on this one (hash does not match):
```c
wyhash("message digest",3,_wyp)=adc146444841c430 // I have value 6e2ff3298208a67c
```

3. hence, can you please:
a)  verify hash value for this case?
b) include your test code in the repository?

Thank you.

**Comment by wangyi-fudan** [comment]
Yes, it is my bug due to the delayed update of test vectors. 
we have test_vector.cpp in this repo to generate test vectors.
Thank you!
